# =============================================================================
# composer-export-example.yaml
# Infrastructure Composer 导出示例 - 简化版三层架构
# =============================================================================
#
# 这个模板演示了 Infrastructure Composer 生成的典型输出。
# 基于 Mini Project 的三层架构设计，已简化以便学习。
#
# 架构：
#   - VPC + 2 Public Subnets + 2 Private Subnets
#   - Internet Gateway + Route Table
#   - Application Load Balancer (Public)
#   - EC2 Instance (Private)
#   - Security Groups
#
# 使用方法：
#   1. CloudFormation Console → Create stack
#   2. 上传此文件
#   3. 填写参数（KeyPair 等）
#   4. 等待 CREATE_COMPLETE
#
# 验证：
#   - cfn-lint composer-export-example.yaml
#
# 清理：
#   - CloudFormation Console → Delete stack
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

# -----------------------------------------------------------------------------
# Description
# -----------------------------------------------------------------------------
# Infrastructure Composer 生成的模板会自动添加描述。
# 这里我们手动添加了更详细的说明。

Description: |
  Infrastructure Composer Export Example
  三层架构：VPC + ALB + EC2
  CloudFormation 课程 Lesson 03 示例模板

# -----------------------------------------------------------------------------
# Metadata
# -----------------------------------------------------------------------------
# Infrastructure Composer 会生成这个 Metadata 块，用于在 Console 中
# 重新打开时恢复可视化布局。

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcCidr
      - Label:
          default: "EC2 Configuration"
        Parameters:
          - InstanceType
          - LatestAmiId

# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------
# 使用参数使模板更灵活，可复用于不同环境。

Parameters:

  # VPC CIDR 块
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
    Description: VPC CIDR Block
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$

  # EC2 实例类型
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 Instance Type
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium

  # 最新 Amazon Linux 2023 AMI (使用 SSM Parameter)
  # 这是 AWS 推荐的方式，自动获取最新 AMI ID
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: Latest Amazon Linux 2023 AMI ID (auto-resolved from SSM)

# -----------------------------------------------------------------------------
# Resources
# -----------------------------------------------------------------------------
# Infrastructure Composer 自动生成的资源定义。
# 包含 VPC、Subnet、IGW、Route Table、ALB、EC2、Security Groups。

Resources:

  # ---------------------------------------------------------------------------
  # VPC
  # ---------------------------------------------------------------------------

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"
        - Key: ManagedBy
          Value: CloudFormation

  # ---------------------------------------------------------------------------
  # Internet Gateway
  # ---------------------------------------------------------------------------

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-IGW"

  # VPC 与 IGW 的关联
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # ---------------------------------------------------------------------------
  # Subnets
  # ---------------------------------------------------------------------------
  # 2 个 Public Subnet（ALB 用）
  # 2 个 Private Subnet（EC2 用）

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select
        - 0
        - !GetAZs ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnet1"

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.2.0/24"
      AvailabilityZone: !Select
        - 1
        - !GetAZs ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnet2"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.3.0/24"
      AvailabilityZone: !Select
        - 0
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PrivateSubnet1"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.4.0/24"
      AvailabilityZone: !Select
        - 1
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PrivateSubnet2"

  # ---------------------------------------------------------------------------
  # Route Tables
  # ---------------------------------------------------------------------------

  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicRT"

  # 默认路由到 IGW
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  # 关联 Public Subnet 到 Public Route Table
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # ---------------------------------------------------------------------------
  # Security Groups
  # ---------------------------------------------------------------------------

  # ALB Security Group - 允许 HTTP/HTTPS 流量
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-ALB-SG"
      GroupDescription: Security group for ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
          Description: Allow HTTP from anywhere
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
          Description: Allow HTTPS from anywhere
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ALB-SG"

  # EC2 Security Group - 只允许来自 ALB 的流量
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-EC2-SG"
      GroupDescription: Security group for EC2 instances
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Allow HTTP from ALB only
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-EC2-SG"

  # ---------------------------------------------------------------------------
  # Application Load Balancer
  # ---------------------------------------------------------------------------

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${AWS::StackName}-ALB"
      Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ALB"

  # ALB Target Group
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${AWS::StackName}-TG"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Targets:
        - Id: !Ref EC2Instance
          Port: 80

  # ALB Listener
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  # ---------------------------------------------------------------------------
  # EC2 Instance
  # ---------------------------------------------------------------------------
  # 简化版：只创建一个实例作为演示

  # IAM Role for EC2 (SSM 访问用)
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-EC2Role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-EC2Role"

  # Instance Profile
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${AWS::StackName}-EC2Profile"
      Roles:
        - !Ref EC2Role

  # EC2 Instance
  # 注意：放在 Public Subnet 以便 UserData 可以访问互联网安装软件
  # 生产环境应使用 Private Subnet + NAT Gateway
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      # 使用 Public Subnet 确保 UserData 可以下载软件包
      # ALB 会将流量转发到此实例
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      # UserData: 安装并启动简单的 Web 服务器
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from CloudFormation!</h1>" > /var/www/html/index.html
          echo "<p>Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id)</p>" >> /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-WebServer"
        - Key: ManagedBy
          Value: CloudFormation

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
# 导出重要的资源信息，方便后续使用或调试。

Outputs:

  VPCId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"

  ALBDNSName:
    Description: ALB DNS Name (访问此地址查看 Web 页面)
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  ALBArn:
    Description: ALB ARN
    Value: !Ref ApplicationLoadBalancer

  EC2InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicSubnets:
    Description: Public Subnet IDs
    Value: !Join
      - ","
      - - !Ref PublicSubnet1
        - !Ref PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnets"

  PrivateSubnets:
    Description: Private Subnet IDs
    Value: !Join
      - ","
      - - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnets"

# =============================================================================
# 关于 Infrastructure Composer 导出
# =============================================================================
#
# Infrastructure Composer 生成的模板特点：
#
# 1. 自动生成 Metadata
#    - 包含可视化布局信息
#    - 允许重新打开时恢复 Canvas
#
# 2. 智能依赖推断
#    - 自动添加 !Ref 和 !GetAtt
#    - 自动处理资源创建顺序
#
# 3. 最佳实践
#    - 使用 !Sub 动态生成名称
#    - 使用 SSM Parameter 获取 AMI ID
#    - 添加必要的 Tags
#
# 本模板在 Composer 导出基础上做了以下优化：
#   - 添加详细中文注释
#   - 优化 Security Group 规则
#   - 添加 UserData 示例
#   - 添加跨栈 Export
#
# =============================================================================
