# =============================================================================
# audit-infra.yaml
# Enterprise Audit Infrastructure - CloudTrail + Config
# =============================================================================
#
# This template deploys enterprise-grade audit infrastructure, including:
# - CloudTrail: Records all AWS API calls
# - AWS Config: Continuous compliance checking
# - S3 Bucket: Stores audit logs
#
# Use cases:
# - Audit response (kansa taiou) - Internal/external audits
# - Evidence management (shouseki kanri) - Audit log retention
# - Compliance - Compliance checking
#
# Usage:
#   1. AWS Console -> CloudFormation -> Create stack
#   2. Upload this file
#   3. Stack name: enterprise-audit
#   4. Configure parameters
#   5. Wait for CREATE_COMPLETE
#
# Cost estimate:
# - CloudTrail: First Trail free, S3 storage costs
# - Config: $0.001/evaluation per rule
# - S3: Storage costs (approx $0.023/GB/month)
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Enterprise Audit Infrastructure - CloudTrail + Config
  Enterprise audit platform for audit response and evidence management
  CloudFormation Course Lesson 06 Example

# -----------------------------------------------------------------------------
# Metadata - Console parameter grouping
# -----------------------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Audit Configuration"
        Parameters:
          - EnableCloudTrail
          - EnableConfig
          - RetentionDays
      - Label:
          default: "Optional Configuration"
        Parameters:
          - EnableLogFileValidation
          - EnableS3DataEvents

# -----------------------------------------------------------------------------
# Parameters - Input parameters
# -----------------------------------------------------------------------------
Parameters:

  EnableCloudTrail:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      Whether to enable CloudTrail

  EnableConfig:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      Whether to enable AWS Config

  RetentionDays:
    Type: Number
    Default: 90
    AllowedValues:
      - 30
      - 60
      - 90
      - 180
      - 365
    Description: |
      Log retention days
      - 30: Development environment
      - 90: General enterprise
      - 365: Financial/compliance requirements

  EnableLogFileValidation:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      Whether to enable log file validation
      Prevents log tampering

  EnableS3DataEvents:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      Whether to record S3 data events
      Note: Incurs additional costs

# -----------------------------------------------------------------------------
# Conditions - Conditional logic
# -----------------------------------------------------------------------------
Conditions:

  # Whether to enable CloudTrail
  CreateCloudTrail: !Equals
    - !Ref EnableCloudTrail
    - "true"

  # Whether to enable Config
  CreateConfig: !Equals
    - !Ref EnableConfig
    - "true"

  # Whether to enable log validation
  EnableValidation: !Equals
    - !Ref EnableLogFileValidation
    - "true"

  # Whether to record S3 data events
  EnableDataEvents: !Equals
    - !Ref EnableS3DataEvents
    - "true"

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------
Resources:

  # ===========================================================================
  # S3 Bucket - Audit log storage
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # Audit log S3 Bucket
  # ---------------------------------------------------------------------------
  AuditLogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain  # Keep logs when Stack is deleted (important!)
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${AWS::StackName}-audit-logs-${AWS::AccountId}'
      # Version control (prevent accidental deletion)
      VersioningConfiguration:
        Status: Enabled
      # Encryption configuration (audit requirement: mandatory)
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # Public access block (security requirement)
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # Lifecycle rules (cost management)
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldLogs
            Status: Enabled
            ExpirationInDays: !Ref RetentionDays
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
          # Transition to Glacier (reduce cost for long-term storage)
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90
      # Tags
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-audit-logs'
        - Key: Environment
          Value: audit
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: "Audit Log Storage"

  # ---------------------------------------------------------------------------
  # S3 Bucket Policy - CloudTrail write permissions
  # ---------------------------------------------------------------------------
  AuditLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateCloudTrail
    Properties:
      Bucket: !Ref AuditLogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # CloudTrail ACL check
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt AuditLogBucket.Arn
            Condition:
              StringEquals:
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${AWS::StackName}-trail'
          # CloudTrail log write
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${AuditLogBucket.Arn}/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${AWS::StackName}-trail'
          # Config log write
          - Sid: AWSConfigWrite
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${AuditLogBucket.Arn}/AWSLogs/${AWS::AccountId}/Config/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt AuditLogBucket.Arn

  # ===========================================================================
  # CloudTrail - API audit logs
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # CloudTrail Trail
  # ---------------------------------------------------------------------------
  AuditTrail:
    Type: AWS::CloudTrail::Trail
    Condition: CreateCloudTrail
    DependsOn: AuditLogBucketPolicy
    Properties:
      TrailName: !Sub '${AWS::StackName}-trail'
      # Target S3 Bucket
      S3BucketName: !Ref AuditLogBucket
      # Include global service events (IAM etc.)
      IncludeGlobalServiceEvents: true
      # Multi-region Trail
      IsMultiRegionTrail: true
      # Enable logging
      IsLogging: true
      # Log file validation (anti-tampering)
      EnableLogFileValidation: !If
        - EnableValidation
        - true
        - false
      # Tags
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-trail'
        - Key: Environment
          Value: audit
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: "API Audit Trail"

  # ===========================================================================
  # AWS Config - Compliance checking
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # Config Recorder IAM Role
  # ---------------------------------------------------------------------------
  ConfigRole:
    Type: AWS::IAM::Role
    Condition: CreateConfig
    Properties:
      RoleName: !Sub '${AWS::StackName}-config-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole
      # S3 write permissions
      Policies:
        - PolicyName: ConfigS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                Resource:
                  - !GetAtt AuditLogBucket.Arn
                  - !Sub '${AuditLogBucket.Arn}/*'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-config-role'
        - Key: ManagedBy
          Value: CloudFormation

  # ---------------------------------------------------------------------------
  # Config Recorder
  # ---------------------------------------------------------------------------
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Condition: CreateConfig
    Properties:
      Name: !Sub '${AWS::StackName}-recorder'
      RoleARN: !GetAtt ConfigRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true

  # ---------------------------------------------------------------------------
  # Config Delivery Channel
  # ---------------------------------------------------------------------------
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Condition: CreateConfig
    DependsOn: AuditLogBucketPolicy
    Properties:
      Name: !Sub '${AWS::StackName}-delivery'
      S3BucketName: !Ref AuditLogBucket
      S3KeyPrefix: AWSLogs
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: TwentyFour_Hours

  # ===========================================================================
  # Config Rules - Compliance rules
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # Rule 1: S3 encryption check
  # ---------------------------------------------------------------------------
  S3EncryptionRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: s3-bucket-server-side-encryption-enabled
      Description: |
        Check if S3 Bucket server-side encryption is enabled
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
      # Check scope: S3 Bucket
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket

  # ---------------------------------------------------------------------------
  # Rule 2: EC2 SSM management check
  # ---------------------------------------------------------------------------
  EC2ManagedBySSMRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: ec2-instance-managed-by-systems-manager
      Description: |
        Check if EC2 instances are managed by Systems Manager
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_MANAGED_BY_SSM
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance

  # ---------------------------------------------------------------------------
  # Rule 3: CloudTrail enabled check
  # ---------------------------------------------------------------------------
  CloudTrailEnabledRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: cloudtrail-enabled
      Description: |
        Check if CloudTrail is enabled
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_ENABLED
      MaximumExecutionFrequency: TwentyFour_Hours

  # ---------------------------------------------------------------------------
  # Rule 4: Root user MFA check
  # ---------------------------------------------------------------------------
  RootMFARule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: root-account-mfa-enabled
      Description: |
        Check if Root account MFA is enabled (important!)
      Source:
        Owner: AWS
        SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED
      MaximumExecutionFrequency: TwentyFour_Hours

  # ---------------------------------------------------------------------------
  # Rule 5: EBS encryption check
  # ---------------------------------------------------------------------------
  EBSEncryptionRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: ec2-ebs-encryption-by-default
      Description: |
        Check if EBS default encryption is enabled
      Source:
        Owner: AWS
        SourceIdentifier: EC2_EBS_ENCRYPTION_BY_DEFAULT
      MaximumExecutionFrequency: TwentyFour_Hours

# -----------------------------------------------------------------------------
# Outputs - Output values
# -----------------------------------------------------------------------------
Outputs:

  AuditLogBucketName:
    Description: "Audit log S3 Bucket name"
    Value: !Ref AuditLogBucket
    Export:
      Name: !Sub '${AWS::StackName}-audit-bucket'

  AuditLogBucketArn:
    Description: "Audit log S3 Bucket ARN"
    Value: !GetAtt AuditLogBucket.Arn

  CloudTrailArn:
    Condition: CreateCloudTrail
    Description: "CloudTrail Trail ARN"
    Value: !GetAtt AuditTrail.Arn

  ConfigRecorderName:
    Condition: CreateConfig
    Description: "Config Recorder name"
    Value: !Ref ConfigRecorder

  AuditDashboardURL:
    Description: "CloudTrail Console URL (quick access)"
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudtrail/home?region=${AWS::Region}#/trails'

  ConfigDashboardURL:
    Condition: CreateConfig
    Description: "Config Console URL (quick access)"
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/config/home?region=${AWS::Region}#/rules'

# =============================================================================
# Japan IT Scenario Notes
# =============================================================================
#
# Audit Response (kansa taiou):
#   - This template meets common audit requirements for Japanese enterprises
#   - CloudTrail: Full API operation audit trail
#   - Config: Continuous compliance checking
#
# Retention period guidelines:
#   - General enterprises: 90 days
#   - Financial industry: 7 years (regulatory requirements)
#   - Government agencies: 5-10 years
#
# Cost management:
#   - Glacier transition reduces long-term storage costs
#   - Disable unnecessary data event recording
#
# =============================================================================
