# =============================================================================
# monitoring-alarms.yaml
# Enterprise Monitoring Alarms Infrastructure - CloudWatch Alarms + SNS
# =============================================================================
#
# This template deploys enterprise-grade monitoring alarm system, including:
# - SNS Topic: Alert notification channel
# - CloudWatch Alarms: Various monitoring alarms
# - Japanese alarm descriptions (Japan enterprise operations scenarios)
#
# Use cases:
# - Operations monitoring (unyou kanshi) - Daily operations monitoring
# - Anomaly detection (ijou kenchi) - Anomaly detection
# - Incident response (shougai taiou) - Incident response
#
# Usage:
#   1. AWS Console -> CloudFormation -> Create stack
#   2. Upload this file
#   3. Stack name: enterprise-monitoring
#   4. Enter notification email
#   5. Wait for CREATE_COMPLETE
#   6. Confirm SNS email subscription
#
# Cost estimate:
# - SNS: $0.50/million requests
# - CloudWatch Alarms: $0.10/alarm/month
# - Total approx $1-2/month
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Enterprise Monitoring Alarms - CloudWatch + SNS
  Enterprise monitoring alarm infrastructure for operations monitoring
  CloudFormation Course Lesson 06 Example

# -----------------------------------------------------------------------------
# Metadata - Console parameter grouping
# -----------------------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Notification Settings"
        Parameters:
          - NotificationEmail
      - Label:
          default: "EC2 Monitoring Thresholds"
        Parameters:
          - CPUThreshold
          - MemoryThreshold
          - DiskThreshold
      - Label:
          default: "RDS Monitoring Thresholds"
        Parameters:
          - RDSCPUThreshold
          - RDSStorageThreshold
          - RDSConnectionsThreshold
      - Label:
          default: "Optional Configuration"
        Parameters:
          - CreateEC2Alarms
          - CreateRDSAlarms
          - CreateBillingAlarm

# -----------------------------------------------------------------------------
# Parameters - Input parameters
# -----------------------------------------------------------------------------
Parameters:

  # Notification settings
  NotificationEmail:
    Type: String
    Description: |
      Alert notification email address
      Recommended: ops-team shared mailbox like ops-team@example.com
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    ConstraintDescription: "Please enter a valid email address"

  # EC2 monitoring thresholds
  CPUThreshold:
    Type: Number
    Default: 80
    MinValue: 50
    MaxValue: 100
    Description: |
      CPU utilization alarm threshold %
      Recommended: 80% (Japanese enterprises typically set 70-85%)

  MemoryThreshold:
    Type: Number
    Default: 85
    MinValue: 50
    MaxValue: 100
    Description: |
      Memory utilization alarm threshold %
      Note: Requires CloudWatch Agent to collect memory metrics

  DiskThreshold:
    Type: Number
    Default: 90
    MinValue: 50
    MaxValue: 100
    Description: |
      Disk utilization alarm threshold %
      Note: Requires CloudWatch Agent to collect disk metrics

  # RDS monitoring thresholds
  RDSCPUThreshold:
    Type: Number
    Default: 80
    MinValue: 50
    MaxValue: 100
    Description: "RDS CPU utilization alarm threshold %"

  RDSStorageThreshold:
    Type: Number
    Default: 10737418240  # 10GB in bytes
    Description: |
      RDS free storage space alarm threshold (bytes)
      Default 10GB, alert when below this value

  RDSConnectionsThreshold:
    Type: Number
    Default: 100
    Description: "RDS database connections alarm threshold"

  # Optional configuration
  CreateEC2Alarms:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: "Whether to create EC2 related alarms"

  CreateRDSAlarms:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: "Whether to create RDS related alarms (requires existing RDS instance)"

  CreateBillingAlarm:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      Whether to create billing alarm
      Note: Only works in us-east-1

# -----------------------------------------------------------------------------
# Conditions - Conditional logic
# -----------------------------------------------------------------------------
Conditions:

  EnableEC2Alarms: !Equals
    - !Ref CreateEC2Alarms
    - "true"

  EnableRDSAlarms: !Equals
    - !Ref CreateRDSAlarms
    - "true"

  EnableBillingAlarm: !And
    - !Equals
      - !Ref CreateBillingAlarm
      - "true"
    - !Equals
      - !Ref AWS::Region
      - us-east-1

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------
Resources:

  # ===========================================================================
  # SNS Topic - Alert notification channel
  # ===========================================================================

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-alerts'
      DisplayName: "CloudFormation Enterprise Alerts"
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-alerts'
        - Key: Environment
          Value: monitoring
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: "Operations Monitoring Alerts"

  # ---------------------------------------------------------------------------
  # Email subscription
  # ---------------------------------------------------------------------------
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  # ---------------------------------------------------------------------------
  # SNS Topic Policy (allow CloudWatch to send notifications)
  # ---------------------------------------------------------------------------
  AlertTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref AlertTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudWatchAlarms
            Effect: Allow
            Principal:
              Service: cloudwatch.amazonaws.com
            Action: sns:Publish
            Resource: !Ref AlertTopic

  # ===========================================================================
  # EC2 Alarms - EC2 monitoring alarms
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # High CPU Alarm
  # ---------------------------------------------------------------------------
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableEC2Alarms
    Properties:
      AlarmName: !Sub '${AWS::StackName}-ec2-high-cpu'
      AlarmDescription: |
        [WARNING] EC2 CPU utilization exceeded threshold

        Response procedure:
        1. Check CloudWatch metrics for details
        2. Check EC2 instance status
        3. Consider scale-up/scale-out if necessary

        Owner: Operations Team
      # Metric configuration
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300  # 5 minutes
      EvaluationPeriods: 2  # 2 consecutive periods
      Threshold: !Ref CPUThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      # Alarm actions
      AlarmActions:
        - !Ref AlertTopic
      OKActions:
        - !Ref AlertTopic
      # ---------------------------------------------------------------------------
      # Dimensions note:
      # ---------------------------------------------------------------------------
      # Dimensions: [] monitors aggregate metrics for all EC2 instances
      #
      # To monitor a specific instance, add:
      #   Dimensions:
      #     - Name: InstanceId
      #       Value: i-0123456789abcdef0
      #
      # Note: Empty Dimensions will show INSUFFICIENT_DATA when no EC2 instances exist
      # This is normal, it will automatically change to OK or ALARM when instances run
      # ---------------------------------------------------------------------------
      Dimensions: []

  # ---------------------------------------------------------------------------
  # Status Check Failed Alarm
  # ---------------------------------------------------------------------------
  StatusCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableEC2Alarms
    Properties:
      AlarmName: !Sub '${AWS::StackName}-ec2-status-check-failed'
      AlarmDescription: |
        [URGENT] EC2 Status Check Failed - Immediate attention required

        Response procedure:
        1. Check instance status in EC2 Console
        2. Check system status/instance status
        3. Reboot instance if necessary
        4. Contact AWS support if hardware failure

        Escalation: Report to supervisor if not resolved within 15 minutes
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed
      Statistic: Maximum
      Period: 60  # 1 minute (urgent)
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # ===========================================================================
  # RDS Alarms - RDS monitoring alarms
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # RDS High CPU Alarm
  # ---------------------------------------------------------------------------
  RDSHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableRDSAlarms
    Properties:
      AlarmName: !Sub '${AWS::StackName}-rds-high-cpu'
      AlarmDescription: |
        [WARNING] RDS CPU utilization exceeded threshold

        Response procedure:
        1. Check SQL load in Performance Insights
        2. Check slow query logs
        3. Consider instance type change if necessary
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: !Ref RDSCPUThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions: []

  # ---------------------------------------------------------------------------
  # RDS Low Storage Alarm
  # ---------------------------------------------------------------------------
  RDSLowStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableRDSAlarms
    Properties:
      AlarmName: !Sub '${AWS::StackName}-rds-low-storage'
      AlarmDescription: |
        [WARNING] RDS Free Storage Space is low

        Response procedure:
        1. Consider deleting unnecessary data
        2. Plan storage capacity expansion
        3. Check auto-scaling settings

        Urgency: Action required within 24 hours
      Namespace: AWS/RDS
      MetricName: FreeStorageSpace
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: !Ref RDSStorageThreshold
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions: []

  # ---------------------------------------------------------------------------
  # RDS High Connections Alarm
  # ---------------------------------------------------------------------------
  RDSHighConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableRDSAlarms
    Properties:
      AlarmName: !Sub '${AWS::StackName}-rds-high-connections'
      AlarmDescription: |
        [WARNING] RDS Database connections approaching limit

        Response procedure:
        1. Check application connection pool settings
        2. Identify and terminate unnecessary connections
        3. Check max_connections parameter
      Namespace: AWS/RDS
      MetricName: DatabaseConnections
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: !Ref RDSConnectionsThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions: []

  # ===========================================================================
  # Billing Alarm - Cost alarm (us-east-1 only)
  # ===========================================================================

  BillingAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableBillingAlarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-billing-alert'
      AlarmDescription: |
        [NOTICE] AWS Estimated Charges exceeded threshold

        Response:
        1. Check cost breakdown in Cost Explorer
        2. Identify and delete unnecessary resources
        3. Report to supervisor if over budget
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Statistic: Maximum
      Period: 21600  # 6 hours
      EvaluationPeriods: 1
      Threshold: 50  # $50
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: Currency
          Value: USD

  # ===========================================================================
  # CloudWatch Dashboard - Monitoring dashboard
  # ===========================================================================

  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${AWS::StackName}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "text",
              "x": 0,
              "y": 0,
              "width": 24,
              "height": 1,
              "properties": {
                "markdown": "# Enterprise Monitoring Dashboard"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 1,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "EC2 CPU Utilization",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/EC2", "CPUUtilization", {"stat": "Average"}]
                ],
                "period": 300,
                "yAxis": {
                  "left": {"min": 0, "max": 100}
                },
                "annotations": {
                  "horizontal": [
                    {
                      "label": "Threshold",
                      "value": ${CPUThreshold}
                    }
                  ]
                }
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 1,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "EC2 Network Traffic",
                "region": "${AWS::Region}",
                "metrics": [
                  ["AWS/EC2", "NetworkIn", {"stat": "Sum", "label": "Network In"}],
                  ["AWS/EC2", "NetworkOut", {"stat": "Sum", "label": "Network Out"}]
                ],
                "period": 300
              }
            },
            {
              "type": "alarm",
              "x": 0,
              "y": 7,
              "width": 24,
              "height": 3,
              "properties": {
                "title": "Active Alarms",
                "alarms": [
                  "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${AWS::StackName}-ec2-high-cpu",
                  "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${AWS::StackName}-ec2-status-check-failed"
                ]
              }
            }
          ]
        }

# -----------------------------------------------------------------------------
# Outputs - Output values
# -----------------------------------------------------------------------------
Outputs:

  AlertTopicArn:
    Description: "Alert SNS Topic ARN"
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${AWS::StackName}-alert-topic'

  AlertTopicName:
    Description: "Alert SNS Topic name"
    Value: !GetAtt AlertTopic.TopicName

  DashboardURL:
    Description: "Monitoring Dashboard URL"
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${AWS::StackName}-dashboard'

  AlarmsConsoleURL:
    Description: "Alarms Console URL"
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#alarmsV2:?~(search~(alarmNamePrefix~(contains~(0~%27${AWS::StackName}))))'

  NotificationEmailAddress:
    Description: "Alert notification email (please confirm subscription!)"
    Value: !Ref NotificationEmail

# =============================================================================
# Japan IT Scenario Notes
# =============================================================================
#
# Operations Monitoring (unyou kanshi):
#   This template provides standard monitoring alarm configuration for Japanese enterprises
#   - Alarm descriptions include response procedures
#   - Clear escalation rules
#
# Alarm severity levels:
#   [URGENT] - Requires immediate response (within 15 minutes)
#   [WARNING] - Requires action same day
#   [NOTICE] - Needs attention, can be scheduled
#
# Shift operations scenario:
#   - Alert emails sent to shared mailbox
#   - On-duty personnel responsible for response
#   - Follow incident response procedures
#
# =============================================================================
