# =============================================================================
# audit-infra.yaml
# 企业级审计基础设施 - CloudTrail + Config
# =============================================================================
#
# 本模板部署企业级审计基础设施，包括：
# - CloudTrail: 记录所有 AWS API 调用
# - AWS Config: 持续合规性检查
# - S3 Bucket: 存储审计日志
#
# 使用场景：
# - 監査対応（かんさたいおう）- 内部/外部审计
# - 証跡管理（しょうせきかんり）- 审计日志保存
# - コンプライアンス - 合规性检查
#
# 使用方法：
#   1. AWS Console → CloudFormation → Create stack
#   2. 上传此文件
#   3. Stack name: enterprise-audit
#   4. 配置参数
#   5. 等待 CREATE_COMPLETE
#
# 费用估算：
# - CloudTrail: 第一个 Trail 免费，S3 存储费用
# - Config: 每条规则 $0.001/evaluation
# - S3: 存储费用（约 $0.023/GB/月）
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Enterprise Audit Infrastructure - CloudTrail + Config
  企業級審計基盤 - 監査対応・証跡管理用
  CloudFormation 課程 Lesson 06 示例

# -----------------------------------------------------------------------------
# Metadata - 控制台参数分组
# -----------------------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "审计配置 (監査設定)"
        Parameters:
          - EnableCloudTrail
          - EnableConfig
          - RetentionDays
      - Label:
          default: "可选配置 (オプション設定)"
        Parameters:
          - EnableLogFileValidation
          - EnableS3DataEvents

# -----------------------------------------------------------------------------
# Parameters - 输入参数
# -----------------------------------------------------------------------------
Parameters:

  EnableCloudTrail:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      是否启用 CloudTrail（CloudTrail を有効化するか）

  EnableConfig:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      是否启用 AWS Config（AWS Config を有効化するか）

  RetentionDays:
    Type: Number
    Default: 90
    AllowedValues:
      - 30
      - 60
      - 90
      - 180
      - 365
    Description: |
      日志保留天数（ログ保持期間）
      - 30: 开发环境
      - 90: 一般企业
      - 365: 金融/合规要求

  EnableLogFileValidation:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      是否启用日志文件验证（ログファイル検証を有効化）
      防止日志被篡改

  EnableS3DataEvents:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: |
      是否记录 S3 数据事件（S3 データイベントを記録）
      注意：会产生额外费用

# -----------------------------------------------------------------------------
# Conditions - 条件逻辑
# -----------------------------------------------------------------------------
Conditions:

  # 是否启用 CloudTrail
  CreateCloudTrail: !Equals
    - !Ref EnableCloudTrail
    - "true"

  # 是否启用 Config
  CreateConfig: !Equals
    - !Ref EnableConfig
    - "true"

  # 是否启用日志验证
  EnableValidation: !Equals
    - !Ref EnableLogFileValidation
    - "true"

  # 是否记录 S3 数据事件
  EnableDataEvents: !Equals
    - !Ref EnableS3DataEvents
    - "true"

# -----------------------------------------------------------------------------
# Resources - 资源定义
# -----------------------------------------------------------------------------
Resources:

  # ===========================================================================
  # S3 Bucket - 审计日志存储
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # 审计日志 S3 Bucket
  # ---------------------------------------------------------------------------
  AuditLogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain  # 删除 Stack 时保留日志（重要！）
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${AWS::StackName}-audit-logs-${AWS::AccountId}'
      # 版本控制（防止误删）
      VersioningConfiguration:
        Status: Enabled
      # 加密配置（监査要件：必須）
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # 公开访问阻止（セキュリティ要件）
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # 生命周期规则（成本管理）
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldLogs
            Status: Enabled
            ExpirationInDays: !Ref RetentionDays
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
          # 转移到 Glacier（长期保存时降低成本）
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90
      # 标签
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-audit-logs'
        - Key: Environment
          Value: audit
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: "監査ログ保存 (Audit Log Storage)"

  # ---------------------------------------------------------------------------
  # S3 Bucket Policy - CloudTrail 写入权限
  # ---------------------------------------------------------------------------
  AuditLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateCloudTrail
    Properties:
      Bucket: !Ref AuditLogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # CloudTrail ACL 检查
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt AuditLogBucket.Arn
            Condition:
              StringEquals:
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${AWS::StackName}-trail'
          # CloudTrail 日志写入
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${AuditLogBucket.Arn}/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${AWS::StackName}-trail'
          # Config 日志写入
          - Sid: AWSConfigWrite
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${AuditLogBucket.Arn}/AWSLogs/${AWS::AccountId}/Config/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt AuditLogBucket.Arn

  # ===========================================================================
  # CloudTrail - API 审计日志
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # CloudTrail Trail
  # ---------------------------------------------------------------------------
  AuditTrail:
    Type: AWS::CloudTrail::Trail
    Condition: CreateCloudTrail
    DependsOn: AuditLogBucketPolicy
    Properties:
      TrailName: !Sub '${AWS::StackName}-trail'
      # 目标 S3 Bucket
      S3BucketName: !Ref AuditLogBucket
      # 包含全局服务事件（IAM 等）
      IncludeGlobalServiceEvents: true
      # 多区域 Trail
      IsMultiRegionTrail: true
      # 启用日志
      IsLogging: true
      # 日志文件验证（防篡改）
      EnableLogFileValidation: !If
        - EnableValidation
        - true
        - false
      # 标签
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-trail'
        - Key: Environment
          Value: audit
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: "API 操作記録 (API Audit Trail)"

  # ===========================================================================
  # AWS Config - 合规性检查
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # Config Recorder IAM Role
  # ---------------------------------------------------------------------------
  ConfigRole:
    Type: AWS::IAM::Role
    Condition: CreateConfig
    Properties:
      RoleName: !Sub '${AWS::StackName}-config-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole
      # S3 写入权限
      Policies:
        - PolicyName: ConfigS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                Resource:
                  - !GetAtt AuditLogBucket.Arn
                  - !Sub '${AuditLogBucket.Arn}/*'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-config-role'
        - Key: ManagedBy
          Value: CloudFormation

  # ---------------------------------------------------------------------------
  # Config Recorder
  # ---------------------------------------------------------------------------
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Condition: CreateConfig
    Properties:
      Name: !Sub '${AWS::StackName}-recorder'
      RoleARN: !GetAtt ConfigRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true

  # ---------------------------------------------------------------------------
  # Config Delivery Channel
  # ---------------------------------------------------------------------------
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Condition: CreateConfig
    DependsOn: AuditLogBucketPolicy
    Properties:
      Name: !Sub '${AWS::StackName}-delivery'
      S3BucketName: !Ref AuditLogBucket
      S3KeyPrefix: AWSLogs
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: TwentyFour_Hours

  # ===========================================================================
  # Config Rules - 合规规则
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # Rule 1: S3 加密检查
  # ---------------------------------------------------------------------------
  S3EncryptionRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: s3-bucket-server-side-encryption-enabled
      Description: |
        S3 バケットのサーバー側暗号化が有効かチェック
        (S3 Bucket 服务端加密检查)
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
      # 检查范围：S3 Bucket
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket

  # ---------------------------------------------------------------------------
  # Rule 2: EC2 SSM 管理检查
  # ---------------------------------------------------------------------------
  EC2ManagedBySSMRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: ec2-instance-managed-by-systems-manager
      Description: |
        EC2 インスタンスが Systems Manager で管理されているかチェック
        (EC2 是否由 SSM 管理)
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_MANAGED_BY_SSM
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance

  # ---------------------------------------------------------------------------
  # Rule 3: CloudTrail 有効化检查
  # ---------------------------------------------------------------------------
  CloudTrailEnabledRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: cloudtrail-enabled
      Description: |
        CloudTrail が有効化されているかチェック
        (CloudTrail 是否启用)
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_ENABLED
      MaximumExecutionFrequency: TwentyFour_Hours

  # ---------------------------------------------------------------------------
  # Rule 4: Root ユーザー MFA 检查
  # ---------------------------------------------------------------------------
  RootMFARule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: root-account-mfa-enabled
      Description: |
        Root アカウントの MFA が有効かチェック
        (Root 账户 MFA 检查 - 重要！)
      Source:
        Owner: AWS
        SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED
      MaximumExecutionFrequency: TwentyFour_Hours

  # ---------------------------------------------------------------------------
  # Rule 5: EBS 暗号化检查
  # ---------------------------------------------------------------------------
  EBSEncryptionRule:
    Type: AWS::Config::ConfigRule
    Condition: CreateConfig
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: ec2-ebs-encryption-by-default
      Description: |
        EBS デフォルト暗号化が有効かチェック
        (EBS 默认加密检查)
      Source:
        Owner: AWS
        SourceIdentifier: EC2_EBS_ENCRYPTION_BY_DEFAULT
      MaximumExecutionFrequency: TwentyFour_Hours

# -----------------------------------------------------------------------------
# Outputs - 输出值
# -----------------------------------------------------------------------------
Outputs:

  AuditLogBucketName:
    Description: "审计日志 S3 Bucket 名称 (監査ログバケット名)"
    Value: !Ref AuditLogBucket
    Export:
      Name: !Sub '${AWS::StackName}-audit-bucket'

  AuditLogBucketArn:
    Description: "审计日志 S3 Bucket ARN"
    Value: !GetAtt AuditLogBucket.Arn

  CloudTrailArn:
    Condition: CreateCloudTrail
    Description: "CloudTrail Trail ARN"
    Value: !GetAtt AuditTrail.Arn

  ConfigRecorderName:
    Condition: CreateConfig
    Description: "Config Recorder 名称"
    Value: !Ref ConfigRecorder

  AuditDashboardURL:
    Description: "CloudTrail Console URL (快速访问)"
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudtrail/home?region=${AWS::Region}#/trails'

  ConfigDashboardURL:
    Condition: CreateConfig
    Description: "Config Console URL (快速访问)"
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/config/home?region=${AWS::Region}#/rules'

# =============================================================================
# 日本 IT 场景说明
# =============================================================================
#
# 監査対応（かんさたいおう）:
#   - 本模板满足日本企业常见的监査要件
#   - CloudTrail: 全 API 操作の証跡
#   - Config: 継続的コンプライアンスチェック
#
# 証跡保持期間の目安:
#   - 一般企業: 90 日
#   - 金融業界: 7 年（規制要件）
#   - 政府機関: 5-10 年
#
# コスト管理:
#   - Glacier 移行で長期保存コストを削減
#   - 不要なデータイベント記録を無効化
#
# =============================================================================
