---
# =============================================================================
# Compliance Report Generation Playbook
# =============================================================================
# Purpose: Gather system security status and generate compliance report
# Version: 1.0
#
# Usage:
#   ansible-playbook generate-report.yaml -i inventory
#
# Output:
#   - /var/log/compliance-report-YYYY-MM-DD.md (on each target)
#   - reports/compliance-report-<hostname>-YYYY-MM-DD.md (on control node)
# =============================================================================

- name: Generate Security Compliance Report
  hosts: all
  become: yes

  vars:
    # Report settings
    report_title: "Security Hardening Compliance Report"
    auditor_name: "Automated Compliance Check"
    local_report_dir: "./reports"

  tasks:
    # =========================================================================
    # Gather SSH Configuration
    # =========================================================================
    - name: Gather SSH configuration
      ansible.builtin.shell: |
        sshd -T 2>/dev/null
      register: sshd_config_raw
      changed_when: false
      failed_when: false

    - name: Parse SSH configuration
      ansible.builtin.set_fact:
        ssh_config:
          PermitRootLogin: "{{ sshd_config_raw.stdout | regex_search('permitrootlogin (\\w+)', '\\1') | first | default('unknown') }}"
          PasswordAuth: "{{ sshd_config_raw.stdout | regex_search('passwordauthentication (\\w+)', '\\1') | first | default('unknown') }}"
          PubkeyAuth: "{{ sshd_config_raw.stdout | regex_search('pubkeyauthentication (\\w+)', '\\1') | first | default('unknown') }}"
          PermitEmptyPasswords: "{{ sshd_config_raw.stdout | regex_search('permitemptypasswords (\\w+)', '\\1') | first | default('unknown') }}"
          MaxAuthTries: "{{ sshd_config_raw.stdout | regex_search('maxauthtries (\\d+)', '\\1') | first | default('6') }}"
          X11Forwarding: "{{ sshd_config_raw.stdout | regex_search('x11forwarding (\\w+)', '\\1') | first | default('unknown') }}"
          PubkeyAcceptedAlgorithms: "{{ sshd_config_raw.stdout | regex_search('pubkeyacceptedalgorithms (.+)', '\\1') | first | default('default') }}"
          HostKeyAlgorithms: "{{ sshd_config_raw.stdout | regex_search('hostkeyalgorithms (.+)', '\\1') | first | default('default') }}"
          KexAlgorithms: "{{ sshd_config_raw.stdout | regex_search('kexalgorithms (.+)', '\\1') | first | default('default') }}"
          Ciphers: "{{ sshd_config_raw.stdout | regex_search('ciphers (.+)', '\\1') | first | default('default') }}"
          MACs: "{{ sshd_config_raw.stdout | regex_search('macs (.+)', '\\1') | first | default('default') }}"

    # =========================================================================
    # Gather SELinux Status
    # =========================================================================
    - name: Check SELinux mode
      ansible.builtin.shell: getenforce 2>/dev/null || echo "disabled"
      register: selinux_mode_raw
      changed_when: false
      failed_when: false

    - name: Check SELinux config
      ansible.builtin.shell: grep "^SELINUX=" /etc/selinux/config 2>/dev/null | cut -d= -f2 || echo "unknown"
      register: selinux_config_raw
      changed_when: false
      failed_when: false

    - name: Set SELinux facts
      ansible.builtin.set_fact:
        selinux_mode: "{{ selinux_mode_raw.stdout | lower }}"
        selinux_config_mode: "{{ selinux_config_raw.stdout | lower }}"
        selinux_policy: "{{ ansible_selinux.type | default('unknown') }}"

    # =========================================================================
    # Gather Audit Status
    # =========================================================================
    - name: Check auditd service status
      ansible.builtin.systemd:
        name: auditd
      register: auditd_service
      failed_when: false

    - name: Set auditd status
      ansible.builtin.set_fact:
        auditd_status: "{{ 'running' if auditd_service.status.ActiveState | default('') == 'active' else 'stopped' }}"

    - name: Count audit rules
      ansible.builtin.shell: auditctl -l 2>/dev/null | wc -l || echo "0"
      register: audit_rules_raw
      changed_when: false
      failed_when: false

    - name: Get audit rules list
      ansible.builtin.shell: auditctl -l 2>/dev/null | head -20 || echo ""
      register: audit_rules_list
      changed_when: false
      failed_when: false

    - name: Set audit facts
      ansible.builtin.set_fact:
        audit_rules_count: "{{ audit_rules_raw.stdout | int }}"
        audit_rules: "{{ audit_rules_list.stdout_lines }}"

    # =========================================================================
    # Gather Firewall Status
    # =========================================================================
    - name: Check nftables status
      ansible.builtin.systemd:
        name: nftables
      register: nftables_service
      failed_when: false

    - name: Check firewalld status
      ansible.builtin.systemd:
        name: firewalld
      register: firewalld_service
      failed_when: false

    - name: Set firewall status
      ansible.builtin.set_fact:
        firewall_status: >-
          {{ 'running' if (nftables_service.status.ActiveState | default('') == 'active' or
                          firewalld_service.status.ActiveState | default('') == 'active')
             else 'stopped' }}
        firewall_service: >-
          {{ 'nftables' if nftables_service.status.ActiveState | default('') == 'active'
             else ('firewalld' if firewalld_service.status.ActiveState | default('') == 'active'
                   else 'none') }}

    # =========================================================================
    # Gather PAM Configuration
    # =========================================================================
    - name: Check pam_faillock
      ansible.builtin.shell: grep -l pam_faillock /etc/pam.d/* 2>/dev/null | wc -l
      register: pam_faillock_raw
      changed_when: false
      failed_when: false

    - name: Check pam_pwquality
      ansible.builtin.shell: grep -l pam_pwquality /etc/pam.d/* 2>/dev/null | wc -l
      register: pam_pwquality_raw
      changed_when: false
      failed_when: false

    - name: Set PAM facts
      ansible.builtin.set_fact:
        pam_faillock_enabled: "{{ (pam_faillock_raw.stdout | int) > 0 }}"
        pam_pwquality_enabled: "{{ (pam_pwquality_raw.stdout | int) > 0 }}"

    # =========================================================================
    # Generate Report
    # =========================================================================
    - name: Generate compliance report on target
      ansible.builtin.template:
        src: compliance-report.j2
        dest: "/var/log/compliance-report-{{ ansible_date_time.date }}.md"
        mode: '0644'

    - name: Create local reports directory
      ansible.builtin.file:
        path: "{{ local_report_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: no
      run_once: true

    - name: Generate compliance report locally
      ansible.builtin.template:
        src: compliance-report.j2
        dest: "{{ local_report_dir }}/compliance-report-{{ inventory_hostname }}-{{ ansible_date_time.date }}.md"
        mode: '0644'
      delegate_to: localhost
      become: no

    - name: Display report location
      ansible.builtin.debug:
        msg: |
          Compliance report generated:
          - Target: /var/log/compliance-report-{{ ansible_date_time.date }}.md
          - Local: {{ local_report_dir }}/compliance-report-{{ inventory_hostname }}-{{ ansible_date_time.date }}.md
