# =============================================================================
# Child Stack - VPC Module (Nested Stack)
# =============================================================================
#
# Child stack template - VPC module, called by parent stack
#
# About Nested Stack child templates:
#   - Must be uploaded to S3 to be referenced by parent stack
#   - Cannot be deployed directly via Console (would miss parent parameter passing)
#   - Can be tested independently, but production use should go through parent
#
# Upload command:
#   aws s3 cp child-vpc.yaml s3://your-bucket/nested-stacks/child-vpc.yaml
#
# Design principles:
#   - Input parameters should be as generic as possible
#   - Output values should expose commonly used attributes
#   - Keep module responsibilities single-purpose
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Child Stack - VPC Module
  This template is designed to be called by a parent stack.
  Upload to S3 before creating the parent stack.

# -----------------------------------------------------------------------------
# Parameters - Input parameters (passed from parent stack)
# -----------------------------------------------------------------------------
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name (passed from parent stack)

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    Description: VPC CIDR block

  PublicSubnetCidr:
    Type: String
    Default: 10.0.1.0/24
    Description: Public Subnet CIDR block

  PrivateSubnetCidr:
    Type: String
    Default: 10.0.2.0/24
    Description: Private Subnet CIDR block

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------
Resources:

  # ---------------------------------------------------------------------------
  # VPC
  # ---------------------------------------------------------------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-vpc'
        - Key: Environment
          Value: !Ref Environment
        - Key: StackType
          Value: Nested-Child
        - Key: ManagedBy
          Value: CloudFormation

  # ---------------------------------------------------------------------------
  # Internet Gateway
  # ---------------------------------------------------------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-igw'
        - Key: Environment
          Value: !Ref Environment

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # ---------------------------------------------------------------------------
  # Public Subnet
  # ---------------------------------------------------------------------------
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-public-subnet'
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Public

  # ---------------------------------------------------------------------------
  # Private Subnet
  # ---------------------------------------------------------------------------
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-subnet'
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private

  # ---------------------------------------------------------------------------
  # Public Route Table
  # ---------------------------------------------------------------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-public-rt'

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ---------------------------------------------------------------------------
  # Private Route Table
  # ---------------------------------------------------------------------------
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-rt'

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

# -----------------------------------------------------------------------------
# Outputs - Output values (for parent stack to use)
# -----------------------------------------------------------------------------
# These outputs are accessed by parent stack via !GetAtt StackName.Outputs.OutputKey
Outputs:

  VpcId:
    Description: VPC ID
    Value: !Ref VPC

  VpcCidr:
    Description: VPC CIDR Block
    Value: !GetAtt VPC.CidrBlock

  SubnetId:
    Description: Public Subnet ID (alias for compatibility)
    Value: !Ref PublicSubnet

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet

  PublicSubnetCidr:
    Description: Public Subnet CIDR
    Value: !Ref PublicSubnetCidr

  PrivateSubnetCidr:
    Description: Private Subnet CIDR
    Value: !Ref PrivateSubnetCidr

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway

  PublicRouteTableId:
    Description: Public Route Table ID
    Value: !Ref PublicRouteTable

  PrivateRouteTableId:
    Description: Private Route Table ID
    Value: !Ref PrivateRouteTable

  AvailabilityZone:
    Description: Availability Zone
    Value: !GetAtt PublicSubnet.AvailabilityZone
