# github-oidc.yaml
# CloudFormation Template: GitHub Actions OIDC Provider Setup
#
# Features:
# - Creates OIDC Identity Provider (trusts GitHub)
# - Creates IAM Role (GitHub Actions can assume)
# - Configures trust policy (restricted to specific repo)
#
# Deploy:
# aws cloudformation deploy \
#   --template-file github-oidc.yaml \
#   --stack-name github-oidc-terraform \
#   --capabilities CAPABILITY_NAMED_IAM \
#   --parameter-overrides \
#     GitHubOrg=your-org \
#     RepoName=your-repo

AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub Actions OIDC Provider and IAM Role for Terraform (no Access Keys needed, uses temporary credentials)

# =============================================================================
# Parameters
# =============================================================================
Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization or username (e.g., your-org or your-username)

  RepoName:
    Type: String
    Description: GitHub repository name (e.g., terraform-infra)

  OIDCAudience:
    Type: String
    Default: sts.amazonaws.com
    Description: OIDC Audience value (default is sts.amazonaws.com, usually no need to change)

  AllowedBranches:
    Type: String
    Default: "*"
    Description: Allowed branch pattern (e.g., main, feature/*, or * for all branches)

# =============================================================================
# Resources
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # OIDC Identity Provider
  # ---------------------------------------------------------------------------
  # Registers GitHub as a trusted identity provider in AWS
  # Only needs to be created once per AWS account, can be shared by multiple roles
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - !Ref OIDCAudience
      # GitHub OIDC thumbprint (certificate fingerprint)
      # Note: AWS no longer validates these for GitHub - kept for backward compatibility
      # Reference: https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Tags:
        - Key: Purpose
          Value: GitHub Actions OIDC
        - Key: ManagedBy
          Value: CloudFormation

  # ---------------------------------------------------------------------------
  # IAM Role for Terraform
  # ---------------------------------------------------------------------------
  # GitHub Actions will assume this role to run Terraform
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub github-actions-terraform-${RepoName}
      Description: !Sub IAM Role for GitHub Actions to run Terraform (Repository: ${GitHubOrg}/${RepoName})

      # Trust policy: Only trust GitHub Actions from specific repository
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                # Audience must match
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                # Subject must match repo and branch
                # Format: repo:org/repo:ref:refs/heads/branch
                # Or: repo:org/repo:pull_request (PR trigger)
                # Or: repo:org/repo:* (all triggers)
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepoName}:*

      # Max session duration: 1 hour (suitable for large Terraform operations)
      MaxSessionDuration: 3600

      Tags:
        - Key: Repository
          Value: !Sub ${GitHubOrg}/${RepoName}
        - Key: ManagedBy
          Value: CloudFormation

  # ---------------------------------------------------------------------------
  # IAM Policy for Terraform
  # ---------------------------------------------------------------------------
  # Grants Terraform permission to operate AWS resources
  # Note: This is example permissions - production should be scoped down as needed
  TerraformPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TerraformAccess
      Roles:
        - !Ref GitHubActionsRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # State backend access
          - Sid: TerraformStateAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::terraform-state-${AWS::AccountId}
              - !Sub arn:aws:s3:::terraform-state-${AWS::AccountId}/*

          # EC2 operations (example)
          - Sid: EC2Access
            Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:CreateTags
              - ec2:RunInstances
              - ec2:TerminateInstances
              - ec2:StartInstances
              - ec2:StopInstances
            Resource: "*"
            Condition:
              StringEquals:
                aws:RequestedRegion: ap-northeast-1

          # S3 operations (example)
          - Sid: S3Access
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:GetBucket*
              - s3:PutBucket*
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::*-${AWS::AccountId}

          # IAM read-only (for data sources)
          - Sid: IAMReadOnly
            Effect: Allow
            Action:
              - iam:GetRole
              - iam:GetPolicy
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
            Resource: "*"

  # ---------------------------------------------------------------------------
  # Separate Plan Role (Optional: Split Plan and Apply permissions)
  # ---------------------------------------------------------------------------
  # Stricter security mode: Plan is read-only, Apply can write
  GitHubActionsPlanRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub github-actions-terraform-plan-${RepoName}
      Description: !Sub Read-only IAM Role for terraform plan (Repository: ${GitHubOrg}/${RepoName})

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                # Only allow PR triggers (pull_request events)
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepoName}:pull_request

      MaxSessionDuration: 3600

      Tags:
        - Key: Repository
          Value: !Sub ${GitHubOrg}/${RepoName}
        - Key: Purpose
          Value: Terraform Plan (Read-Only)
        - Key: ManagedBy
          Value: CloudFormation

  # Plan Role read-only policy
  TerraformPlanPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TerraformPlanAccess
      Roles:
        - !Ref GitHubActionsPlanRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # State read-only
          - Sid: TerraformStateReadOnly
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::terraform-state-${AWS::AccountId}
              - !Sub arn:aws:s3:::terraform-state-${AWS::AccountId}/*

          # All resources read-only
          - Sid: ReadOnlyAccess
            Effect: Allow
            Action:
              - ec2:Describe*
              - s3:Get*
              - s3:List*
              - iam:Get*
              - iam:List*
              - rds:Describe*
              - elasticloadbalancing:Describe*
            Resource: "*"

# =============================================================================
# Outputs
# =============================================================================
Outputs:
  OIDCProviderArn:
    Description: OIDC Provider ARN
    Value: !GetAtt GitHubOIDCProvider.Arn
    Export:
      Name: !Sub ${AWS::StackName}-OIDCProviderArn

  RoleArn:
    Description: IAM Role ARN for Terraform (full access) - Add to GitHub Secrets as AWS_ROLE_ARN
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RoleArn

  PlanRoleArn:
    Description: IAM Role ARN for Terraform Plan (read-only) - For stricter permission separation
    Value: !GetAtt GitHubActionsPlanRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PlanRoleArn

  TrustPolicyExample:
    Description: Trust policy Subject format examples
    Value: !Sub |
      repo:${GitHubOrg}/${RepoName}:ref:refs/heads/main - main branch only
      repo:${GitHubOrg}/${RepoName}:pull_request - PRs only
      repo:${GitHubOrg}/${RepoName}:* - all triggers
