# =============================================================================
# first-stack.yaml
# CloudFormation Getting Started - Your First Stack
# =============================================================================
#
# This template creates a simple S3 Bucket to demonstrate CloudFormation basics.
#
# Usage:
#   1. AWS Console -> CloudFormation -> Create stack
#   2. Upload this file
#   3. Stack name: my-first-stack
#   4. Wait for CREATE_COMPLETE
#
# Cleanup:
#   1. CloudFormation Console -> Select Stack -> Delete
#   2. Wait for DELETE_COMPLETE
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

# -----------------------------------------------------------------------------
# Description - Template description
# -----------------------------------------------------------------------------
# Best practice: Write clear descriptions for team understanding.
# This text is displayed in the CloudFormation Console.

Description: |
  My First CloudFormation Stack - S3 Bucket
  CloudFormation Course Lesson 00 Example Template
  Creates an S3 Bucket with tags

# -----------------------------------------------------------------------------
# Metadata - Optional metadata section
# -----------------------------------------------------------------------------
# Used to provide Console with extra info like parameter grouping.
# Not used in this lesson, covered in later lessons.

# Metadata:
#   AWS::CloudFormation::Interface:
#     ParameterGroups:
#       - ...

# -----------------------------------------------------------------------------
# Parameters - Input parameters (optional)
# -----------------------------------------------------------------------------
# This lesson uses hardcoded values. Parameters for template reuse
# will be covered in later lessons.

# Parameters:
#   BucketNamePrefix:
#     Type: String
#     Default: my-first-cfn-bucket

# -----------------------------------------------------------------------------
# Resources - Resource definitions (REQUIRED)
# -----------------------------------------------------------------------------
# This is the core section defining AWS resources to create.
#
# Format:
#   LogicalID:              # Your defined name, unique in template
#     Type: AWS::Service::Resource  # Resource type
#     Properties:           # Resource properties
#       PropertyName: PropertyValue

Resources:

  # ---------------------------------------------------------------------------
  # S3 Bucket - Main resource
  # ---------------------------------------------------------------------------
  #
  # Resource Type: AWS::S3::Bucket
  # Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
  #
  # Logical ID: MyFirstBucket
  #   - Your defined name, unique within this template
  #   - Used by other resources to reference (e.g., !Ref MyFirstBucket)
  #   - Different from Physical ID (actual AWS resource name)

  MyFirstBucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName - S3 bucket name
      #
      # !Sub is an intrinsic function for string substitution
      # ${AWS::AccountId} is a pseudo parameter, replaced with current AWS account ID
      #
      # Result example: my-first-cfn-bucket-123456789012
      #
      # Why use account ID?
      #   - S3 bucket names must be globally unique
      #   - Using account ID avoids naming conflicts
      BucketName: !Sub 'my-first-cfn-bucket-${AWS::AccountId}'

      # PublicAccessBlockConfiguration - Block public access (security best practice)
      #
      # Since 2023, AWS blocks all public access by default.
      # Explicitly configuring this is an enterprise security compliance best practice.
      #
      # Japan IT scenarios:
      #   - Financial/government projects must block public access
      #   - cfn-guard rules typically check this configuration
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      # Tags - Resource tags
      #
      # Tags are key-value pairs used for:
      #   - Resource classification and discovery
      #   - Cost Allocation
      #   - Access control (tag-based IAM policies)
      #   - Automation
      #
      # Japan IT scenarios:
      #   - Environment: dev/stg/prod
      #   - Project: project code
      #   - Owner: responsible person
      Tags:
        - Key: Name
          Value: My First CloudFormation Bucket
        - Key: Environment
          Value: learning
        - Key: Purpose
          Value: CloudFormation Course Practice

# -----------------------------------------------------------------------------
# Outputs - Output values (optional)
# -----------------------------------------------------------------------------
# Output values are used for:
#   - Displaying important info in Console
#   - Cross-stack references
#   - CLI/SDK resource info retrieval
#
# Format:
#   OutputLogicalID:
#     Description: Description text
#     Value: Output value
#     Export:               # Optional: export for other stacks
#       Name: Export name

Outputs:

  # Bucket Name
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref MyFirstBucket
    # !Ref returns the physical ID of the resource
    # For S3 Bucket, physical ID is the bucket name

  # Bucket ARN
  BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt MyFirstBucket.Arn
    # !GetAtt retrieves a specific attribute of a resource
    # Syntax: !GetAtt LogicalID.AttributeName
    #
    # Common attributes:
    #   - Arn: Amazon Resource Name
    #   - DomainName: Domain name
    #   - RegionalDomainName: Regional domain name

  # Bucket Domain Name
  BucketDomainName:
    Description: S3 Bucket Domain Name
    Value: !GetAtt MyFirstBucket.DomainName

# -----------------------------------------------------------------------------
# About Intrinsic Functions
# -----------------------------------------------------------------------------
#
# This template uses the following intrinsic functions:
#
# !Sub (Fn::Sub)
#   - String substitution
#   - ${variable} is replaced with actual value
#   - Supports pseudo parameters and resource references
#
# !Ref (Fn::Ref)
#   - Returns physical ID of resource or parameter value
#   - For S3 Bucket: returns bucket name
#   - For EC2 Instance: returns instance ID
#
# !GetAtt (Fn::GetAtt)
#   - Gets specific attribute of a resource
#   - Supported attributes vary by resource type, see docs
#
# More intrinsic functions covered in later lessons.
#
# -----------------------------------------------------------------------------
# Pseudo Parameters
# -----------------------------------------------------------------------------
#
# AWS built-in parameters, available without definition:
#
#   AWS::AccountId    - Current AWS account ID (e.g., 123456789012)
#   AWS::Region       - Current region (e.g., ap-northeast-1)
#   AWS::StackName    - Current stack name
#   AWS::StackId      - Current stack ID
#   AWS::NoValue      - Used in conditions, means "don't set this property"
#
# Pseudo parameter use cases covered in later lessons.
#
# =============================================================================
