# =============================================================================
# drift-demo.yaml
# CloudFormation Drift Detection Demo Template
# =============================================================================
#
# This template creates a simple EC2 instance to demonstrate Drift Detection.
#
# Usage:
#   1. AWS Console -> CloudFormation -> Create stack
#   2. Upload this file
#   3. Stack name: drift-demo-stack
#   4. Wait for CREATE_COMPLETE
#
# Drift exercise:
#   1. Manually modify instance tags in EC2 Console
#   2. Return to CloudFormation -> Stack actions -> Detect drift
#   3. View Drift results
#   4. Choose fix method (Update stack or update template)
#
# Cleanup:
#   1. CloudFormation Console -> Select Stack -> Delete
#   2. Wait for DELETE_COMPLETE
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

# -----------------------------------------------------------------------------
# Description - Template description
# -----------------------------------------------------------------------------

Description: |
  CloudFormation Drift Detection Demo
  Lesson 05 - Drift Detection and Resource Import Demo Template
  Creates an EC2 instance with tags for demonstrating Drift Detection

# -----------------------------------------------------------------------------
# Metadata - Console UI enhancement
# -----------------------------------------------------------------------------
# Use Metadata to make Console interface more user-friendly

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "EC2 Configuration"
        Parameters:
          - InstanceType
          - Environment
    ParameterLabels:
      InstanceType:
        default: "Instance Type"
      Environment:
        default: "Environment"

# -----------------------------------------------------------------------------
# Parameters - Input parameters
# -----------------------------------------------------------------------------

Parameters:
  # EC2 instance type
  # Use t3.micro to stay within free tier
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: |
      EC2 instance type.
      t3.micro is free tier eligible (750 hours per month).

  # Environment tag
  # This parameter will be used to demonstrate Drift
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: |
      Environment type (for Tag).
      During exercise, manually modify this tag to create Drift.

  # Latest Amazon Linux 2023 AMI (using SSM Parameter)
  # Use SSM Parameter instead of hardcoded AMI ID to always get latest Amazon Linux 2023
  # This is AWS recommended best practice, avoiding Stack creation failure due to expired AMI
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: |
      Latest Amazon Linux 2023 AMI ID (auto-resolved from SSM Parameter Store).
      AWS automatically updates this parameter, no need to manually maintain AMI ID.

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------

Resources:

  # ---------------------------------------------------------------------------
  # EC2 Instance - Demo instance
  # ---------------------------------------------------------------------------
  #
  # This EC2 instance will be used to demonstrate Drift Detection:
  # 1. Set Environment tag to parameter value when created
  # 2. Manually modify tag in Console
  # 3. Run Drift Detection to detect changes
  # 4. Fix via Update Stack or update template to accept changes

  DemoInstance:
    Type: AWS::EC2::Instance
    Properties:
      # Instance type (from parameter)
      InstanceType: !Ref InstanceType

      # AMI ID (from SSM Parameter)
      # Use SSM Parameter to auto-get latest AMI, avoid hardcoding expiration
      ImageId: !Ref LatestAmiId

      # Tags - Primary detection target for Drift Detection
      #
      # Exercise steps:
      # 1. After creation, modify Environment tag in EC2 Console
      # 2. Add new tag like ModifiedBy: console-user
      # 3. Run Detect drift to view differences
      Tags:
        # Instance name
        - Key: Name
          Value: drift-demo-instance

        # Environment tag (from parameter)
        # This is the main target for Drift exercise
        - Key: Environment
          Value: !Ref Environment

        # Management identifier
        - Key: ManagedBy
          Value: CloudFormation

        # Purpose identifier
        - Key: Purpose
          Value: Drift Detection Demo

        # Course identifier
        - Key: Course
          Value: CloudFormation-Lesson05

  # ---------------------------------------------------------------------------
  # Security Group - Security group
  # ---------------------------------------------------------------------------
  #
  # Create an empty security group (no inbound rules)
  # Only for satisfying EC2 instance network configuration needs

  DemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Drift Detection demo (no inbound rules)
      GroupName: !Sub 'drift-demo-sg-${AWS::StackName}'
      Tags:
        - Key: Name
          Value: drift-demo-sg
        - Key: ManagedBy
          Value: CloudFormation

# -----------------------------------------------------------------------------
# Outputs - Output values
# -----------------------------------------------------------------------------
# Output important information for subsequent operations and verification

Outputs:

  # Instance ID
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref DemoInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  # Instance private IP
  PrivateIp:
    Description: EC2 Private IP Address
    Value: !GetAtt DemoInstance.PrivateIp

  # Environment tag value (for comparing Drift)
  EnvironmentTag:
    Description: |
      Environment tag value (as defined in template).
      Compare this with actual EC2 tags after manual modification.
    Value: !Ref Environment

  # Security Group ID
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref DemoSecurityGroup

# -----------------------------------------------------------------------------
# Drift Detection Notes
# -----------------------------------------------------------------------------
#
# CloudFormation Drift Detection supports detecting the following property changes:
#
# EC2 Instance:
#   - Tags
#   - InstanceType (requires stopping instance)
#   - SecurityGroupIds
#   - Other partial properties
#
# Properties not supported for detection:
#   - EBS volume content
#   - Instance internal configuration
#   - CloudWatch metrics
#
# Full supported list reference:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift-resource-list.html
#
# -----------------------------------------------------------------------------
# Japan IT Scenarios
# -----------------------------------------------------------------------------
#
# Typical use cases for Drift Detection in Japanese enterprises:
#
# 1. Incident Response (shougai taiou)
#    Direct Console modifications during nighttime emergencies
#    Track changes via Drift Detection the next day
#
# 2. Change Management (henkou kanri)
#    Drift records as change evidence
#    Used with change management tickets
#
# 3. Audit Response (kansa taiou)
#    Regular Drift detection reports
#    Prove effectiveness of configuration management
#
# =============================================================================
