# =============================================================================
# import-s3.yaml
# CloudFormation Resource Import Demo Template - S3 Bucket (Phase 1: Import)
# =============================================================================
#
# IMPORTANT: This is a minimal template for Import operation
#
# AWS CloudFormation has the following limitations during Import:
#   - Cannot have Outputs
#   - Parameters cannot be modified during Import
#   - Can only define resources to import
#
# Workflow (two phases):
#   Phase 1: Use this template to import resources
#   Phase 2: Use import-s3-complete.yaml to update Stack and add Outputs
#
# Usage:
#   1. AWS Console -> CloudFormation -> Create stack
#   2. Select "With existing resources (import resources)"
#   3. Upload this file
#   4. On Identify resources page, fill in:
#      - Logical ID: ImportedBucket
#      - Resource type: AWS::S3::Bucket
#      - Identifier property: BucketName
#      - Identifier value: my-legacy-bucket-{your-account-id}
#   5. Stack name: imported-bucket-stack
#   6. Complete Import
#   7. Run Detect drift to confirm IN_SYNC
#   8. (Optional) Update Stack using import-s3-complete.yaml to add Outputs
#
# CLI method:
#   # Phase 1: Import
#   ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
#   aws cloudformation create-change-set \
#     --stack-name imported-bucket-stack \
#     --change-set-name import-legacy-bucket \
#     --change-set-type IMPORT \
#     --template-body file://import-s3.yaml \
#     --resources-to-import "[{\"ResourceType\":\"AWS::S3::Bucket\",\"LogicalResourceId\":\"ImportedBucket\",\"ResourceIdentifier\":{\"BucketName\":\"my-legacy-bucket-${ACCOUNT_ID}\"}}]"
#
#   # Wait for ChangeSet creation to complete
#   aws cloudformation wait change-set-create-complete \
#     --stack-name imported-bucket-stack \
#     --change-set-name import-legacy-bucket
#
#   # Execute ChangeSet
#   aws cloudformation execute-change-set \
#     --stack-name imported-bucket-stack \
#     --change-set-name import-legacy-bucket
#
# Cleanup:
#   1. CloudFormation Console -> Select Stack -> Delete
#   2. Due to DeletionPolicy: Retain, Bucket will not be deleted
#   3. Manually delete Bucket: aws s3 rb s3://my-legacy-bucket-{account-id}
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

Description: |
  CloudFormation Resource Import Demo - S3 Bucket (Phase 1)
  Minimal template for Import operation, no Outputs
  After Import, use import-s3-complete.yaml to update and add Outputs

# -----------------------------------------------------------------------------
# Resources - Resource definitions (minimal configuration)
# -----------------------------------------------------------------------------
# Only basic resource properties need to be defined for Import
# More properties (like Tags) can be added in updates after Import

Resources:

  ImportedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # BucketName must exactly match existing Bucket name
      BucketName: !Sub 'my-legacy-bucket-${AWS::AccountId}'

# =============================================================================
# About Import Limitations
# =============================================================================
#
# 1. Outputs not supported
#    Import operation does not allow templates to contain Outputs section
#    Solution: After Import completes, update Stack to add Outputs
#
# 2. Resource identifier must exactly match
#    S3 Bucket uses BucketName as identifier
#    Other resource types have different identifiers:
#      - EC2 Instance: InstanceId
#      - RDS: DBInstanceIdentifier
#      - Lambda: FunctionName
#
# 3. Resource types that support Import
#    Not all resources support Import, full list reference:
#    https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
#
# =============================================================================
