# =============================================================================
# CloudFormation Template Complete Structure Example
# =============================================================================
#
# This file demonstrates all CloudFormation Template Sections for learning.
# In actual projects, you don't need all Sections - only Resources is required.
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

# -----------------------------------------------------------------------------
# Description - Template description
# -----------------------------------------------------------------------------
# Brief explanation of template purpose, displayed in CloudFormation Console
Description: |
  CloudFormation Template Complete Structure Example
  Demonstrates all Sections: Parameters, Mappings, Conditions, Resources, Outputs, Metadata

# -----------------------------------------------------------------------------
# Metadata - Optional metadata section
# -----------------------------------------------------------------------------
# Used for Console UI grouping, hints etc. Does not affect resource creation
Metadata:
  # AWS::CloudFormation::Interface customizes Console parameter input UI
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Basic Settings"
        Parameters:
          - Environment
          - ProjectName
      - Label:
          default: "EC2 Settings"
        Parameters:
          - InstanceType
          - KeyPairName
      - Label:
          default: "Network Settings"
        Parameters:
          - VpcId
          - SubnetId
    ParameterLabels:
      Environment:
        default: "Environment Type"
      ProjectName:
        default: "Project Name"
      InstanceType:
        default: "Instance Type"

# -----------------------------------------------------------------------------
# Parameters - Input parameters (optional)
# -----------------------------------------------------------------------------
# Let users fill in values when creating Stack, enabling template reuse
Parameters:
  # Basic String type
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment type (dev/stg/prod)
    ConstraintDescription: Please select dev, stg, or prod

  ProjectName:
    Type: String
    Default: myproject
    MinLength: 3
    MaxLength: 20
    AllowedPattern: ^[a-z][a-z0-9-]*$
    Description: Project name (lowercase letters, numbers, hyphens only)
    ConstraintDescription: Must start with lowercase letter, only lowercase letters, numbers, hyphens allowed

  # Number type
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: EC2 Instance Type

  # AWS-specific types (Console shows dropdown menu)
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair for EC2

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for EC2 placement

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for EC2 placement

  # SSM Parameter type (reads value from SSM)
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: AMI ID to use (from SSM Parameter)

# -----------------------------------------------------------------------------
# Mappings - Static lookup tables (optional)
# -----------------------------------------------------------------------------
# Used to store unchanging mappings like region AMI IDs, environment configs
Mappings:
  # Region AMI mapping (backup option, prefer SSM Parameter)
  RegionAMI:
    ap-northeast-1:
      AmazonLinux2023: ami-0d52744d6551d851e
      Ubuntu22: ami-0bba69335379e17f8
    ap-northeast-3:
      AmazonLinux2023: ami-0599b6e53ca798bb2
      Ubuntu22: ami-0e9085e5dd6a47b69
    us-east-1:
      AmazonLinux2023: ami-0c02fb55956c7d316
      Ubuntu22: ami-0c7217cdde317cfec

  # Environment configuration mapping
  EnvironmentConfig:
    dev:
      InstanceType: t3.micro
      VolumeSize: 8
      Monitoring: false
    stg:
      InstanceType: t3.small
      VolumeSize: 20
      Monitoring: true
    prod:
      InstanceType: t3.medium
      VolumeSize: 50
      Monitoring: true

# -----------------------------------------------------------------------------
# Conditions - Conditional logic (optional)
# -----------------------------------------------------------------------------
# Decide whether to create resources or set properties based on parameter values
Conditions:
  # Is production environment
  IsProd: !Equals [!Ref Environment, prod]

  # Is not production environment
  IsNotProd: !Not [!Equals [!Ref Environment, prod]]

  # Is development environment
  IsDev: !Equals [!Ref Environment, dev]

  # Whether to create EIP (only in prod and stg)
  CreateEIP: !Or
    - !Equals [!Ref Environment, prod]
    - !Equals [!Ref Environment, stg]

  # Combined condition example
  IsProdInTokyo: !And
    - !Equals [!Ref Environment, prod]
    - !Equals [!Ref 'AWS::Region', ap-northeast-1]

# -----------------------------------------------------------------------------
# Resources - Resource definitions (REQUIRED!)
# -----------------------------------------------------------------------------
# Define AWS resources to create
Resources:
  # Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${Environment}-sg'
      GroupDescription: !Sub 'Security group for ${ProjectName} ${Environment}'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-sg'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # Use SSM Parameter to get latest AMI
      ImageId: !Ref LatestAmiId
      # Use different Instance Type based on environment
      InstanceType: !FindInMap [EnvironmentConfig, !Ref Environment, InstanceType]
      KeyName: !Ref KeyPairName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      # Conditionally enable detailed monitoring (enabled in prod/stg)
      Monitoring: !FindInMap [EnvironmentConfig, !Ref Environment, Monitoring]
      # Root volume configuration
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !FindInMap [EnvironmentConfig, !Ref Environment, VolumeSize]
            VolumeType: gp3
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-instance'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation
        # Using Pseudo Parameters
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: Region
          Value: !Ref AWS::Region

  # Elastic IP - Only created in prod/stg environments
  ElasticIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIP
    Properties:
      InstanceId: !Ref EC2Instance
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-eip'
        - Key: Environment
          Value: !Ref Environment

# -----------------------------------------------------------------------------
# Outputs - Output values (optional)
# -----------------------------------------------------------------------------
# Output important info, can be referenced by other Stacks
Outputs:
  # Instance ID
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  # Security Group ID
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  # Private IP (always available)
  PrivateIP:
    Description: EC2 Private IP Address
    Value: !GetAtt EC2Instance.PrivateIp

  # Public IP (conditional output)
  PublicIP:
    Description: Public IP Address
    Value: !If
      - CreateEIP
      - !Ref ElasticIP                    # Return EIP when available
      - !GetAtt EC2Instance.PublicIp      # Return dynamic IP when no EIP
    Condition: CreateEIP
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'

  # Instance ARN (built using !Sub and Pseudo Parameters)
  InstanceArn:
    Description: EC2 Instance ARN
    Value: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${EC2Instance}'

  # SSH connection command (convenient to copy)
  SSHCommand:
    Description: SSH connection command
    Value: !If
      - CreateEIP
      - !Sub 'ssh -i ${KeyPairName}.pem ec2-user@${ElasticIP}'
      - !Sub 'ssh -i ${KeyPairName}.pem ec2-user@${EC2Instance.PublicIp}'

  # Environment info
  EnvironmentInfo:
    Description: Environment configuration summary
    Value: !Sub |
      Environment: ${Environment}
      Project: ${ProjectName}
      Instance Type: ${InstanceType}
      Region: ${AWS::Region}
