AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Terraform Learning Lab Environment
  - EC2 instance with Terraform, AWS CLI, Git pre-installed
  - SSM Session Manager access (no SSH key needed)
  - VS Code Remote-SSH compatible
  - IAM Role with scoped permissions for learning exercises

Parameters:
  InstanceType:
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: EC2 instance type (t3.small recommended for comfortable development)

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR block

  SubnetCidr:
    Type: String
    Default: 10.0.1.0/24
    Description: Public subnet CIDR block

  Project:
    Type: String
    Default: terraform-course
    Description: Project name for tagging

Resources:
  # ===========================================================================
  # VPC & Networking
  # ===========================================================================

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${Project}-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Project}-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref SubnetCidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${Project}-public-subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${Project}-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ===========================================================================
  # Security Group
  # ===========================================================================

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Terraform lab instance
      VpcId: !Ref VPC
      # No inbound rules - SSM Session Manager doesn't need them
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-sg

  # ===========================================================================
  # IAM Role for EC2 (SSM + Terraform permissions)
  # ===========================================================================

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Project}-TerraformLabRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # SSM Session Manager access
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        # Terraform learning permissions (scoped)
        - PolicyName: TerraformLearningPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 permissions (for Terraform exercises)
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:GetBucketLocation
                  - s3:GetBucketVersioning
                  - s3:PutBucketVersioning
                  - s3:GetBucketTagging
                  - s3:PutBucketTagging
                  - s3:ListBucket
                  - s3:GetBucketPolicy
                  - s3:GetBucketAcl
                  - s3:GetBucketCORS
                  - s3:GetBucketWebsite
                  - s3:GetBucketLogging
                  - s3:GetLifecycleConfiguration
                  - s3:GetReplicationConfiguration
                  - s3:GetEncryptionConfiguration
                  - s3:GetBucketRequestPayment
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketPublicAccessBlock
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetObjectLockConfiguration
                  - s3:GetBucketOwnershipControls
                  - s3:PutBucketOwnershipControls
                Resource:
                  - arn:aws:s3:::my-first-terraform-*
                  - arn:aws:s3:::terraform-course-*
                  - arn:aws:s3:::terraform-state-*

              # EC2 permissions (for later lessons)
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: '*'

              - Effect: Allow
                Action:
                  - ec2:CreateVpc
                  - ec2:DeleteVpc
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateSubnet
                  - ec2:DeleteSubnet
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:CreateInternetGateway
                  - ec2:DeleteInternetGateway
                  - ec2:AttachInternetGateway
                  - ec2:DetachInternetGateway
                  - ec2:CreateRouteTable
                  - ec2:DeleteRouteTable
                  - ec2:CreateRoute
                  - ec2:DeleteRoute
                  - ec2:AssociateRouteTable
                  - ec2:DisassociateRouteTable
                  - ec2:AllocateAddress
                  - ec2:ReleaseAddress
                  - ec2:CreateNatGateway
                  - ec2:DeleteNatGateway
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:RequestedRegion: ap-northeast-1

              # DynamoDB permissions (for state locking)
              - Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - dynamodb:TagResource
                  - dynamodb:UntagResource
                Resource:
                  - !Sub arn:aws:dynamodb:ap-northeast-1:${AWS::AccountId}:table/terraform-*

              # IAM read permissions (for viewing roles)
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - sts:GetCallerIdentity
                Resource: '*'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # ===========================================================================
  # EC2 Instance
  # ===========================================================================

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: terraform-dev
        - Key: Project
          Value: !Ref Project
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -ex

          # Update system
          dnf update -y

          # Install required packages
          dnf install -y git jq unzip

          # Install Terraform
          dnf install -y yum-utils
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
          dnf install -y terraform

          # Verify installations
          terraform version
          aws --version
          git --version

          # Set hostname
          hostnamectl set-hostname terraform-dev

          # Configure ec2-user environment
          cat >> /home/ec2-user/.bashrc << 'EOF'

          # Terraform aliases
          alias tf='terraform'
          alias tfi='terraform init'
          alias tfp='terraform plan'
          alias tfa='terraform apply'
          alias tfd='terraform destroy'
          alias tfo='terraform output'
          alias tfs='terraform state'

          # Prompt with Terraform workspace
          export PS1='[\u@\h:\w $(terraform workspace show 2>/dev/null || echo "N/A")]\$ '

          # Editor
          export EDITOR=vim
          EOF

          # Create welcome message
          cat > /etc/motd << 'EOF'

          ╔═══════════════════════════════════════════════════════════════╗
          ║           Terraform Learning Lab Environment                   ║
          ╠═══════════════════════════════════════════════════════════════╣
          ║  Terraform: $(terraform version -json | jq -r '.terraform_version')                                           ║
          ║  AWS CLI:   $(aws --version | cut -d' ' -f1 | cut -d'/' -f2)                                           ║
          ║                                                               ║
          ║  Quick Start:                                                 ║
          ║    cd ~/terraform-examples/lesson-01-first-resource/code      ║
          ║    terraform init                                             ║
          ║    terraform plan                                             ║
          ║                                                               ║
          ║  Aliases: tf, tfi, tfp, tfa, tfd, tfo, tfs                    ║
          ╚═══════════════════════════════════════════════════════════════╝

          EOF

          # Signal completion
          echo "UserData script completed successfully" > /var/log/userdata-complete.log

Outputs:
  InstanceId:
    Description: EC2 Instance ID (use this for VS Code SSH config)
    Value: !Ref Instance

  InstancePrivateIp:
    Description: Private IP address of the instance
    Value: !GetAtt Instance.PrivateIp

  VpcId:
    Description: VPC ID
    Value: !Ref VPC

  SubnetId:
    Description: Subnet ID
    Value: !Ref PublicSubnet

  SSMConnectCommand:
    Description: Command to connect via SSM
    Value: !Sub 'aws ssm start-session --target ${Instance} --region ${AWS::Region}'

  VSCodeSSHConfig:
    Description: SSH config for VS Code Remote
    Value: !Sub |
      Host terraform-lab
        HostName ${Instance}
        User ec2-user
        ProxyCommand aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p' --region ${AWS::Region}
