# github-oidc.yaml
# CloudFormation: GitHub Actions OIDC Provider and IAM Role
#
# This template creates:
# 1. OIDC Identity Provider (trusts GitHub)
# 2. IAM Role (GitHub Actions can assume)
# 3. Policies for Terraform operations
#
# Deploy:
#   aws cloudformation deploy \
#     --template-file github-oidc.yaml \
#     --stack-name github-oidc-terraform \
#     --capabilities CAPABILITY_NAMED_IAM \
#     --parameter-overrides \
#       GitHubOrg=YOUR_USERNAME \
#       RepoName=YOUR_REPO_NAME

AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub Actions OIDC Provider and IAM Role for Terraform CI/CD

# =============================================================================
# Parameters
# =============================================================================
Parameters:
  GitHubOrg:
    Type: String
    Description: Your GitHub username or organization name

  RepoName:
    Type: String
    Description: Your GitHub repository name

  OIDCAudience:
    Type: String
    Default: sts.amazonaws.com
    Description: OIDC Audience (keep default)

# =============================================================================
# Resources
# =============================================================================
Resources:
  # ---------------------------------------------------------------------------
  # OIDC Identity Provider
  # ---------------------------------------------------------------------------
  # Registers GitHub as a trusted identity provider in AWS
  # One per AWS account (shared by all repos)
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - !Ref OIDCAudience
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Tags:
        - Key: Purpose
          Value: GitHub Actions OIDC

  # ---------------------------------------------------------------------------
  # IAM Role for GitHub Actions
  # ---------------------------------------------------------------------------
  # GitHub Actions will assume this role to run Terraform
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub github-actions-${RepoName}
      Description: !Sub IAM Role for GitHub Actions (${GitHubOrg}/${RepoName})

      # Trust policy: Only trust GitHub Actions from YOUR repo
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                # Only YOUR repo can assume this role
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepoName}:*

      MaxSessionDuration: 3600

      Tags:
        - Key: Repository
          Value: !Sub ${GitHubOrg}/${RepoName}

  # ---------------------------------------------------------------------------
  # IAM Policy for Terraform
  # ---------------------------------------------------------------------------
  TerraformPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TerraformAccess
      Roles:
        - !Ref GitHubActionsRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # S3 operations (for demo bucket)
          - Sid: S3Access
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:Get*
              - s3:Put*
              - s3:List*
            Resource:
              - arn:aws:s3:::cicd-demo-*
              - arn:aws:s3:::cicd-demo-*/*

          # Read-only for data sources
          - Sid: ReadOnlyAccess
            Effect: Allow
            Action:
              - iam:Get*
              - iam:List*
              - ec2:Describe*
            Resource: "*"

# =============================================================================
# Outputs
# =============================================================================
Outputs:
  RoleArn:
    Description: |
      IAM Role ARN - Add this to GitHub Secrets as AWS_ROLE_ARN
    Value: !GetAtt GitHubActionsRole.Arn

  OIDCProviderArn:
    Description: OIDC Provider ARN
    Value: !GetAtt GitHubOIDCProvider.Arn

  NextStep:
    Description: Next step after deployment
    Value: !Sub |
      1. Copy the RoleArn output above
      2. Go to GitHub repo > Settings > Secrets > Actions
      3. Add secret: AWS_ROLE_ARN = <the RoleArn value>
