# =============================================================================
# Multi-Environment EC2 Template - Mini Project
# =============================================================================
#
# This template demonstrates CloudFormation core features:
#   - Parameters: Accept user input (Environment, KeyPairName)
#   - Mappings: Region AMI mapping + Environment config mapping
#   - Conditions: Conditionally create EIP (only in prod)
#   - Intrinsic functions: !Ref, !GetAtt, !Sub, !FindInMap, !If
#   - Outputs: Export resource information
#
# Usage:
#   1. Open CloudFormation Console
#   2. Create Stack > Upload a template file
#   3. Fill in Parameters (choose dev or prod)
#   4. Observe Resources differences
#
# Notes:
#   - Need to create EC2 Key Pair first
#   - Uses default VPC and Subnet
#   - Remember to delete Stack when done!
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Multi-environment EC2 template demonstrating Parameters, Mappings, and Conditions.
  Creates t3.micro for dev, t3.small + EIP for prod.

# -----------------------------------------------------------------------------
# Metadata - Console UI enhancement
# -----------------------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Settings"
        Parameters:
          - Environment
      - Label:
          default: "EC2 Settings"
        Parameters:
          - KeyPairName
    ParameterLabels:
      Environment:
        default: "Select Environment (dev/prod)"
      KeyPairName:
        default: "SSH Key Pair"

# -----------------------------------------------------------------------------
# Parameters - User input
# -----------------------------------------------------------------------------
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: |
      Select environment type:
      - dev: t3.micro, no EIP, 8GB disk
      - prod: t3.small, with EIP, 20GB disk
    ConstraintDescription: Please select either dev or prod

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select key pair for SSH connection

# -----------------------------------------------------------------------------
# Mappings - Static lookup tables
# -----------------------------------------------------------------------------
Mappings:
  # Region AMI mapping
  # Using Amazon Linux 2023 (AMI IDs as of 2024-12)
  # Note: AMI IDs change over time, use SSM Parameter for production
  RegionAMI:
    ap-northeast-1:    # Tokyo
      AmazonLinux2023: ami-0d52744d6551d851e
    ap-northeast-3:    # Osaka
      AmazonLinux2023: ami-0599b6e53ca798bb2
    us-east-1:         # Virginia
      AmazonLinux2023: ami-0c02fb55956c7d316
    us-west-2:         # Oregon
      AmazonLinux2023: ami-0b8c6b923777519db

  # Environment configuration mapping
  EnvironmentConfig:
    dev:
      InstanceType: t3.micro
      VolumeSize: 8
      NameSuffix: development
    prod:
      InstanceType: t3.small
      VolumeSize: 20
      NameSuffix: production

# -----------------------------------------------------------------------------
# Conditions - Conditional logic
# -----------------------------------------------------------------------------
Conditions:
  # Create EIP for prod environment
  IsProd: !Equals
    - !Ref Environment
    - prod

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------
Resources:
  # Security Group - Allow SSH access
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Security group for ${Environment} EC2 instance'
      SecurityGroupIngress:
        # SSH access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access from anywhere
        # HTTP access (optional)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-web-server-sg'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # Use !FindInMap to get AMI ID from Mappings
      ImageId: !FindInMap
        - RegionAMI
        - !Ref 'AWS::Region'
        - AmazonLinux2023

      # Use !FindInMap to get Instance Type based on environment
      InstanceType: !FindInMap
        - EnvironmentConfig
        - !Ref Environment
        - InstanceType

      # Reference Parameter
      KeyName: !Ref KeyPairName

      # Reference Security Group (using !Ref)
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup

      # Root volume configuration
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !FindInMap
              - EnvironmentConfig
              - !Ref Environment
              - VolumeSize
            VolumeType: gp3
            DeleteOnTermination: true
            Encrypted: true

      # Tags - Demonstrating !Sub and !Ref usage
      Tags:
        - Key: Name
          # !Sub substitutes variables
          Value: !Sub '${Environment}-web-server'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
        # Using Pseudo Parameters
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: AccountId
          Value: !Ref AWS::AccountId
        - Key: Region
          Value: !Ref AWS::Region

  # Elastic IP - Only created in prod environment
  ElasticIP:
    Type: AWS::EC2::EIP
    Condition: IsProd    # Conditional creation!
    Properties:
      InstanceId: !Ref EC2Instance
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-web-server-eip'
        - Key: Environment
          Value: !Ref Environment

# -----------------------------------------------------------------------------
# Outputs - Output information
# -----------------------------------------------------------------------------
Outputs:
  # Instance ID - Using !Ref to get primary identifier
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  # Private IP - Using !GetAtt to get attribute
  PrivateIP:
    Description: Private IP Address
    Value: !GetAtt EC2Instance.PrivateIp

  # Availability Zone - !GetAtt for other attributes
  AvailabilityZone:
    Description: Availability Zone
    Value: !GetAtt EC2Instance.AvailabilityZone

  # Public IP - Using !If for conditional output
  PublicIP:
    Description: Public IP Address (EIP for prod, dynamic for dev)
    Value: !If
      - IsProd                              # Condition name
      - !Ref ElasticIP                      # true: return EIP
      - !GetAtt EC2Instance.PublicIp        # false: return dynamic Public IP

  # Security Group ID
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref InstanceSecurityGroup

  # Instance ARN - Using !Sub with Pseudo Parameters
  InstanceArn:
    Description: EC2 Instance ARN
    Value: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${EC2Instance}'

  # SSH connection command - Convenient for users to copy
  SSHCommand:
    Description: SSH connection command
    Value: !If
      - IsProd
      - !Sub 'ssh -i ${KeyPairName}.pem ec2-user@${ElasticIP}'
      - !Sub 'ssh -i ${KeyPairName}.pem ec2-user@${EC2Instance.PublicIp}'

  # Environment configuration summary
  ConfigSummary:
    Description: Environment configuration summary
    Value: !Sub 'Environment: ${Environment}, Region: ${AWS::Region}'
