# =============================================================================
# first-stack.yaml
# CloudFormation 入门 - 第一个 Stack
# =============================================================================
#
# 本模板创建一个简单的 S3 Bucket，用于演示 CloudFormation 基础概念。
#
# 使用方法：
#   1. AWS Console → CloudFormation → Create stack
#   2. 上传此文件
#   3. Stack name: my-first-stack
#   4. 等待 CREATE_COMPLETE
#
# 清理方法：
#   1. CloudFormation Console → 选择 Stack → Delete
#   2. 等待 DELETE_COMPLETE
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

# -----------------------------------------------------------------------------
# Description - 模板描述
# -----------------------------------------------------------------------------
# 建议每个模板都写清晰的描述，方便团队理解和管理。
# 在 Console 中会显示这个描述。

Description: |
  My First CloudFormation Stack - S3 Bucket
  CloudFormation 课程 Lesson 00 示例模板
  创建一个带标签的 S3 Bucket

# -----------------------------------------------------------------------------
# Metadata - 元数据（可选）
# -----------------------------------------------------------------------------
# 用于向 Console 提供额外信息，如参数分组、标签等。
# 本课暂不使用，后续课程会介绍。

# Metadata:
#   AWS::CloudFormation::Interface:
#     ParameterGroups:
#       - ...

# -----------------------------------------------------------------------------
# Parameters - 输入参数（可选）
# -----------------------------------------------------------------------------
# 本课使用硬编码值，后续课程会介绍 Parameters 实现模板复用。

# Parameters:
#   BucketNamePrefix:
#     Type: String
#     Default: my-first-cfn-bucket

# -----------------------------------------------------------------------------
# Resources - 资源定义（必须）
# -----------------------------------------------------------------------------
# 这是模板的核心部分，定义要创建的 AWS 资源。
#
# 格式：
#   LogicalID:              # 逻辑 ID（你定义的名称，在模板中唯一）
#     Type: AWS::服务::资源  # 资源类型
#     Properties:           # 资源属性
#       属性名: 属性值

Resources:

  # ---------------------------------------------------------------------------
  # S3 Bucket - 主资源
  # ---------------------------------------------------------------------------
  #
  # 资源类型: AWS::S3::Bucket
  # 文档: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
  #
  # Logical ID: MyFirstBucket
  #   - 这是你定义的名称，在模板中唯一
  #   - 用于其他资源引用（如 !Ref MyFirstBucket）
  #   - 不同于 Physical ID（AWS 实际创建的资源名称）

  MyFirstBucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName - S3 桶名称
      #
      # !Sub 是内置函数，用于字符串替换
      # ${AWS::AccountId} 是伪参数，自动替换为当前 AWS 账户 ID
      #
      # 结果示例: my-first-cfn-bucket-123456789012
      #
      # 为什么用账户 ID？
      #   - S3 桶名称必须全球唯一
      #   - 使用账户 ID 避免命名冲突
      BucketName: !Sub 'my-first-cfn-bucket-${AWS::AccountId}'

      # Tags - 资源标签
      #
      # 标签是键值对，用于：
      #   - 资源分类和查找
      #   - 成本分配（Cost Allocation）
      #   - 访问控制（基于标签的 IAM 策略）
      #   - 自动化处理
      #
      # 日本 IT 场景：
      #   - 環境 (Environment): dev/stg/prod
      #   - プロジェクト (Project): 项目代号
      #   - 担当者 (Owner): 负责人
      Tags:
        - Key: Name
          Value: My First CloudFormation Bucket
        - Key: Environment
          Value: learning
        - Key: Purpose
          Value: CloudFormation 课程练习
        - Key: ManagedBy
          Value: CloudFormation

# -----------------------------------------------------------------------------
# Outputs - 输出值（可选）
# -----------------------------------------------------------------------------
# 输出值用于：
#   - 在 Console 显示重要信息
#   - 其他 Stack 引用（跨栈引用）
#   - CLI/SDK 获取资源信息
#
# 格式：
#   OutputLogicalID:
#     Description: 描述
#     Value: 输出值
#     Export:               # 可选：导出给其他 Stack 使用
#       Name: 导出名称

Outputs:

  # Bucket 名称
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref MyFirstBucket
    # !Ref 返回资源的物理 ID
    # 对于 S3 Bucket，物理 ID 就是桶名称

  # Bucket ARN
  BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt MyFirstBucket.Arn
    # !GetAtt 获取资源的特定属性
    # 语法: !GetAtt LogicalID.AttributeName
    #
    # 常用属性：
    #   - Arn: Amazon Resource Name
    #   - DomainName: 域名
    #   - RegionalDomainName: 区域域名

  # Bucket Domain Name
  BucketDomainName:
    Description: S3 Bucket Domain Name
    Value: !GetAtt MyFirstBucket.DomainName

# -----------------------------------------------------------------------------
# 关于内置函数
# -----------------------------------------------------------------------------
#
# 本模板使用了以下内置函数（Intrinsic Functions）：
#
# !Sub (Fn::Sub)
#   - 字符串替换
#   - ${变量名} 会被替换为实际值
#   - 支持伪参数和其他资源引用
#
# !Ref (Fn::Ref)
#   - 返回资源的物理 ID 或参数值
#   - 对于 S3 Bucket: 返回桶名称
#   - 对于 EC2 Instance: 返回实例 ID
#
# !GetAtt (Fn::GetAtt)
#   - 获取资源的特定属性
#   - 每种资源支持的属性不同，参考文档
#
# 后续课程会详细介绍更多内置函数。
#
# -----------------------------------------------------------------------------
# 伪参数（Pseudo Parameters）
# -----------------------------------------------------------------------------
#
# AWS 提供的内置参数，无需定义即可使用：
#
#   AWS::AccountId    - 当前 AWS 账户 ID (如 123456789012)
#   AWS::Region       - 当前区域 (如 ap-northeast-1)
#   AWS::StackName    - 当前 Stack 名称
#   AWS::StackId      - 当前 Stack ID
#   AWS::NoValue      - 条件中使用，表示不设置该属性
#
# 后续课程会详细介绍伪参数的使用场景。
#
# =============================================================================
