# =============================================================================
# changeset-demo.yaml
# CloudFormation ChangeSet Demo Template
# =============================================================================
#
# This template demonstrates ChangeSet workflow:
#   1. Create initial Stack
#   2. Modify template (add tags)
#   3. Create ChangeSet to preview changes
#   4. Execute ChangeSet
#
# Japan enterprise scenarios:
#   - ChangeSet = Change approval documentation material
#   - Screenshots saved as audit evidence
#   - Replacement = Requires risk assessment
#
# Usage:
#   1. AWS Console -> CloudFormation -> Create stack
#   2. Upload this file
#   3. Stack name: changeset-demo
#   4. Wait for CREATE_COMPLETE
#   5. Modify template (add Owner tag)
#   6. Stack actions -> Create change set for current stack
#   7. Preview changes -> Execute change set
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

Description: |
  ChangeSet Demo - Demonstrates CloudFormation safe update workflow
  This template is for learning ChangeSet usage

# -----------------------------------------------------------------------------
# Metadata - Console interface metadata
# -----------------------------------------------------------------------------

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Basic Settings"
        Parameters:
          - Environment
          - Version

# -----------------------------------------------------------------------------
# Parameters - Input parameters
# -----------------------------------------------------------------------------

Parameters:
  Environment:
    Type: String
    Default: learning
    AllowedValues:
      - learning
      - development
      - staging
      - production
    Description: Environment name

  Version:
    Type: String
    Default: v1
    Description: |
      Template version. Change from v1 to v2 when demonstrating ChangeSet.

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------

Resources:

  # ---------------------------------------------------------------------------
  # S3 Bucket - Demo bucket
  # ---------------------------------------------------------------------------
  #
  # This Bucket is used to demonstrate ChangeSet workflow:
  #   - Modifying Tags: In-Place update (safe)
  #   - Modifying BucketName: Replace (dangerous! data loss)
  #
  # [IMPORTANT] Observe in ChangeSet preview:
  #   - Replacement: False = Safe (In-Place)
  #   - Replacement: True = Dangerous (delete and recreate)

  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName - S3 bucket name
      #
      # Uses account ID to ensure global uniqueness
      # Note: Modifying BucketName causes Replacement!
      BucketName: !Sub 'changeset-demo-${AWS::AccountId}'

      # Tags - Resource tags
      #
      # Modifying tags is an In-Place update, no service disruption
      # This is a safe scenario for demonstrating ChangeSet
      #
      # Japan IT scenarios:
      #   - Standard tags are required (Environment, ManagedBy, etc.)
      #   - Cost allocation tags for project-wise cost management
      Tags:
        - Key: Name
          Value: ChangeSet Demo Bucket
        - Key: Environment
          Value: !Ref Environment
        - Key: Version
          Value: !Ref Version
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: ChangeSet Demo

        # ---------------------------------------------------------------------------
        # Demo: Uncomment these tags and create ChangeSet to observe changes
        # ---------------------------------------------------------------------------
        # - Key: Owner
        #   Value: your-name
        # - Key: UpdatedAt
        #   Value: 2025-01-01

      # PublicAccessBlock - Block public access (security best practice)
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

# -----------------------------------------------------------------------------
# Outputs - Output values
# -----------------------------------------------------------------------------

Outputs:

  BucketName:
    Description: S3 Bucket Name
    Value: !Ref DemoBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt DemoBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  BucketDomainName:
    Description: S3 Bucket Domain Name
    Value: !GetAtt DemoBucket.DomainName

  CurrentVersion:
    Description: Current template version
    Value: !Ref Version

# =============================================================================
# ChangeSet Demo Steps
# =============================================================================
#
# Step 1: Create initial Stack
#   - Use default parameters to create Stack
#   - Observe CREATE_COMPLETE
#
# Step 2: Modify template to prepare ChangeSet
#   - Method A: Change Version parameter value (v1 -> v2)
#   - Method B: Uncomment Owner/UpdatedAt tags
#
# Step 3: Create ChangeSet
#   - Stack actions -> Create change set for current stack
#   - Upload modified template
#   - Change set name: add-owner-tag (or other descriptive name)
#
# Step 4: Preview changes
#   - Observe Changes section
#   - Confirm Action: Modify
#   - Confirm Replacement: False (safe)
#   - [IMPORTANT] Screenshot saved as change management evidence
#
# Step 5: Execute ChangeSet
#   - Execute change set
#   - Observe UPDATE_IN_PROGRESS -> UPDATE_COMPLETE
#
# Step 6: Verify update
#   - S3 Console confirm tags updated
#   - Outputs confirm version number updated
#
# =============================================================================
# Dangerous Operation Demo (Optional)
# =============================================================================
#
# If you want to demonstrate Replacement scenario:
#
# 1. Modify BucketName:
#    BucketName: !Sub 'changeset-demo-new-${AWS::AccountId}'
#
# 2. Create ChangeSet and observe:
#    - Replacement: True (dangerous!)
#    - Old Bucket will be deleted, data lost!
#
# 3. In Japan enterprises this requires:
#    - Risk assessment
#    - Special approval
#    - Backup confirmation
#
# =============================================================================
