# =============================================================================
# deletion-policy-demo.yaml
# DeletionPolicy and UpdateReplacePolicy Demo Template
# =============================================================================
#
# This template demonstrates how to protect critical resources:
#   - DeletionPolicy: Resource handling when Stack is deleted
#   - UpdateReplacePolicy: Resource handling when update causes Replace
#
# Three policies:
#   - Delete (default): Delete resource
#   - Retain: Keep resource (requires manual management afterward)
#   - Snapshot: Create snapshot then delete (RDS, EBS, Neptune, Redshift only)
#
# Japan enterprise scenarios:
#   - Production databases must use DeletionPolicy: Snapshot
#   - Important S3 buckets should use DeletionPolicy: Retain
#   - Backup confirmation required before deletion
#
# Usage:
#   1. Create Stack: deletion-policy-demo
#   2. Confirm both Buckets created successfully
#   3. Delete Stack
#   4. Observe: TempBucket deleted, ImportantBucket retained
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

Description: |
  DeletionPolicy Demo - Demonstrates how to protect critical resources
  Template for verifying DeletionPolicy and UpdateReplacePolicy behavior

# -----------------------------------------------------------------------------
# Parameters - Input parameters
# -----------------------------------------------------------------------------

Parameters:
  Environment:
    Type: String
    Default: learning
    AllowedValues:
      - learning
      - development
      - staging
      - production
    Description: Environment name

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------

Resources:

  # ---------------------------------------------------------------------------
  # TempBucket - Temporary Bucket (default behavior, will be deleted)
  # ---------------------------------------------------------------------------
  #
  # This Bucket uses default DeletionPolicy: Delete
  # When Stack is deleted, this Bucket will also be deleted
  #
  # Use cases:
  #   - Temporary file storage
  #   - Build artifacts
  #   - Regeneratable data
  #   - Learning/testing environments

  TempBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Delete  # Default value, can be omitted
    Properties:
      BucketName: !Sub 'temp-bucket-${AWS::AccountId}'
      Tags:
        - Key: Name
          Value: Temporary Bucket (will be deleted with stack)
        - Key: Environment
          Value: !Ref Environment
        - Key: Protected
          Value: 'false'
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Description
          Value: Deleted when stack is deleted. For temporary files.

      # Security configuration
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ---------------------------------------------------------------------------
  # ImportantBucket - Important Bucket (protected, will not be deleted)
  # ---------------------------------------------------------------------------
  #
  # This Bucket has DeletionPolicy: Retain set
  # When Stack is deleted, this Bucket will be retained
  #
  # [IMPORTANT]
  # - Bucket will be detached from CloudFormation management
  # - Requires manual management or re-import afterward
  # - Will continue to incur storage costs
  #
  # Use cases:
  #   - Production data
  #   - User uploaded content
  #   - Log archives
  #   - Data retention for compliance

  ImportantBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain              # Retain when Stack deleted
    UpdateReplacePolicy: Retain         # Also retain when update causes Replace
    Properties:
      BucketName: !Sub 'important-bucket-${AWS::AccountId}'
      Tags:
        - Key: Name
          Value: Important Bucket (will be retained)
        - Key: Environment
          Value: !Ref Environment
        - Key: Protected
          Value: 'true'
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Description
          Value: Retained after stack deletion. Manual management required.

      # Version control (best practice for important data)
      VersioningConfiguration:
        Status: Enabled

      # Security configuration
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ---------------------------------------------------------------------------
  # Demo comment: DeletionPolicy: Snapshot for RDS databases
  # ---------------------------------------------------------------------------
  #
  # Recommended configuration for production RDS databases:
  #
  # ProductionDatabase:
  #   Type: AWS::RDS::DBInstance
  #   DeletionPolicy: Snapshot           # Create snapshot before deletion
  #   UpdateReplacePolicy: Snapshot      # Also create snapshot before Replace
  #   Properties:
  #     DBInstanceIdentifier: prod-db
  #     DBInstanceClass: db.t3.micro
  #     Engine: mysql
  #     MasterUsername: admin
  #     MasterUserPassword: '{{resolve:secretsmanager:prod-db-password}}'
  #     AllocatedStorage: 20
  #     Tags:
  #       - Key: Environment
  #         Value: production
  #       - Key: Protected
  #         Value: 'true'
  #
  # Snapshot naming convention:
  #   - Auto-generated: {stack-name}-{resource-id}-{timestamp}
  #   - Snapshot retention policy needs separate configuration

# -----------------------------------------------------------------------------
# Outputs - Output values
# -----------------------------------------------------------------------------

Outputs:

  TempBucketName:
    Description: |
      Temporary Bucket name (will be deleted when Stack deleted)
    Value: !Ref TempBucket

  TempBucketArn:
    Description: Temporary Bucket ARN
    Value: !GetAtt TempBucket.Arn

  ImportantBucketName:
    Description: |
      Important Bucket name (will be retained when Stack deleted!)
    Value: !Ref ImportantBucket

  ImportantBucketArn:
    Description: Important Bucket ARN
    Value: !GetAtt ImportantBucket.Arn

  ProtectionNote:
    Description: Protection explanation
    Value: |
      TempBucket: DeletionPolicy=Delete (default) - will be deleted with stack
      ImportantBucket: DeletionPolicy=Retain - will be retained after stack deletion

# =============================================================================
# DeletionPolicy Detailed Explanation
# =============================================================================
#
# 1. Delete (default)
#    - Resource deleted when Stack deleted
#    - Use for: Temporary resources, rebuildable resources
#    - Risk: Permanent data loss
#
# 2. Retain
#    - Resource retained when Stack deleted
#    - Resource detached from CloudFormation management
#    - Requires manual management or re-import afterward
#    - Use for: Production data, important logs
#
# 3. Snapshot (only supported by some resource types)
#    - Create snapshot before deleting resource when Stack deleted
#    - Supported resource types:
#      * AWS::RDS::DBInstance
#      * AWS::RDS::DBCluster
#      * AWS::EC2::Volume
#      * AWS::Neptune::DBCluster
#      * AWS::Redshift::Cluster
#    - Use for: Databases, storage requiring backup
#
# =============================================================================
# UpdateReplacePolicy Detailed Explanation
# =============================================================================
#
# Behavior when update operation causes resource Replace:
#
# 1. Some property changes trigger Replace
#    - Example: Changing S3 BucketName, RDS DBInstanceIdentifier
#
# 2. Replace process:
#    - CloudFormation creates new resource
#    - Updates dependencies
#    - Handles old resource according to UpdateReplacePolicy
#
# 3. UpdateReplacePolicy options:
#    - Delete: Delete old resource (default)
#    - Retain: Keep old resource
#    - Snapshot: Create snapshot then delete (RDS/EBS etc.)
#
# =============================================================================
# Japan Enterprise Best Practices
# =============================================================================
#
# 1. Production databases
#    DeletionPolicy: Snapshot
#    UpdateReplacePolicy: Snapshot
#
# 2. User data S3 Buckets
#    DeletionPolicy: Retain
#    UpdateReplacePolicy: Retain
#
# 3. Log archives
#    DeletionPolicy: Retain
#    (Compliance may require retention for years)
#
# 4. Temporary/development resources
#    DeletionPolicy: Delete (default)
#    (Cost management, avoid resource accumulation)
#
# =============================================================================
# How to Clean Up Retained Resources
# =============================================================================
#
# After Stack deletion, Retained resources need manual cleanup:
#
# S3 Bucket:
#   # First empty the Bucket
#   aws s3 rm s3://important-bucket-YOUR_ACCOUNT_ID --recursive
#   # Then delete the Bucket
#   aws s3 rb s3://important-bucket-YOUR_ACCOUNT_ID
#
# Or use --force to do it in one step:
#   aws s3 rb s3://important-bucket-YOUR_ACCOUNT_ID --force
#
# =============================================================================
