# =============================================================================
# failure-demo.yaml
# Failure Lab - Intentional Rollback Demonstration
# =============================================================================
#
# This template intentionally contains a failing resource to demonstrate:
#   1. CloudFormation automatic rollback mechanism
#   2. Error information in Stack Events
#   3. ROLLBACK_COMPLETE state
#
# [Teaching Purpose]
#   - Observe how CloudFormation handles failures
#   - Understand the value of automatic rollback (vs Terraform)
#   - Learn to read Stack Events for debugging
#
# Japan enterprise scenarios:
#   - Automatic rollback is a major advantage of CloudFormation
#   - Safe even when production deployment fails
#   - No manual intervention required during incident response
#
# Usage:
#   1. Create Stack: failure-lab
#   2. Observe Events: CREATE_IN_PROGRESS -> CREATE_FAILED -> ROLLBACK
#   3. Final state: ROLLBACK_COMPLETE
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Failure Lab - Demonstrates CloudFormation automatic rollback mechanism
  This template intentionally fails to demonstrate automatic rollback

# -----------------------------------------------------------------------------
# Resources - Resource definitions
# -----------------------------------------------------------------------------

Resources:

  # ---------------------------------------------------------------------------
  # DemoBucket - This will be created successfully
  # ---------------------------------------------------------------------------
  #
  # S3 Bucket creation is fast and will succeed first
  # But when EC2 fails later, this Bucket will also be rolled back (deleted)

  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'failure-lab-${AWS::AccountId}'
      Tags:
        - Key: Name
          Value: Failure Lab Bucket
        - Key: Purpose
          Value: Rollback demo bucket

  # ---------------------------------------------------------------------------
  # FailingInstance - This will fail (using invalid AMI ID)
  # ---------------------------------------------------------------------------
  #
  # [Intentional Error]
  # Using a non-existent AMI ID, EC2 creation will definitely fail
  #
  # Observation points:
  #   1. Events show error: "AMI ami-invalid-id-12345 does not exist"
  #   2. CloudFormation automatically starts ROLLBACK
  #   3. Already created DemoBucket gets deleted
  #   4. Final state: ROLLBACK_COMPLETE

  FailingInstance:
    Type: AWS::EC2::Instance
    DependsOn: DemoBucket              # Ensure Bucket is created first
    Properties:
      # Invalid AMI ID - intentional error!
      ImageId: ami-invalid-id-12345
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: This will fail

# =============================================================================
# Expected Stack Events Sequence
# =============================================================================
#
# Time     Logical ID           Status                  Notes
# ----     ----------           ------                  -----
# T+0      failure-lab          CREATE_IN_PROGRESS      User initiates creation
# T+1      DemoBucket           CREATE_IN_PROGRESS      Start creating Bucket
# T+3      DemoBucket           CREATE_COMPLETE         Bucket created successfully
# T+4      FailingInstance      CREATE_IN_PROGRESS      Start creating EC2
# T+5      FailingInstance      CREATE_FAILED           AMI does not exist, failed!
# T+6      failure-lab          ROLLBACK_IN_PROGRESS    Automatic rollback starts
# T+7      FailingInstance      DELETE_IN_PROGRESS      Delete failed instance
# T+8      FailingInstance      DELETE_COMPLETE         Done
# T+9      DemoBucket           DELETE_IN_PROGRESS      Rollback deletes Bucket
# T+11     DemoBucket           DELETE_COMPLETE         Done
# T+12     failure-lab          ROLLBACK_COMPLETE       Rollback complete
#
# =============================================================================
# Comparison with Terraform Behavior
# =============================================================================
#
# Terraform when encountering failure:
#   1. Stops execution
#   2. Already created resources are retained (no automatic rollback)
#   3. Need manual terraform destroy or fix and retry
#
# CloudFormation when encountering failure:
#   1. Automatic rollback
#   2. Already created resources are deleted
#   3. Returns to pre-creation state
#
# [Conclusion] CloudFormation's automatic rollback is critical for production!
#
# =============================================================================
# Other Methods to Trigger Failure (for reference)
# =============================================================================
#
# 1. Invalid Security Group ID
#    SecurityGroupIds:
#      - sg-invalid-12345
#
# 2. Non-existent Subnet
#    SubnetId: subnet-invalid-12345
#
# 3. Insufficient Permissions
#    # Use resources requiring special permissions, but IAM not authorized
#
# 4. Resource Limits
#    # Exceed VPC count limit, EIP limit, etc.
#
# 5. Invalid IAM Role
#    IamInstanceProfile: invalid-role-name
#
# =============================================================================
